### ISSUE TITLE
function cannot be pickled for mongodb

### ISSUE THREAD

**Issue by mcgibbon** [maxpumperla/hyperas#105]
When using hyperopt.mongoexp.MongoTrials for parallelism, I am getting the same error as expressed in [this StackOverflow thread](https://stackoverflow.com/questions/41373885/hyperopt-mongotrials-issue-with-pickle-attributeerror-module-object-has-no-a). In my case, because I am using hyperas, the error says `hyperopt.mongoexp:job exception: No module named temp_model`.

I believe I have made my function self-sufficient, and I have installed dill. Is there anything done to the function by hyperas that would make it temp_function impossible to pickle? Has anyone else successfully used hyperas [with mongodb](https://github.com/hyperopt/hyperopt/wiki/Parallelizing-Evaluations-During-Search-via-MongoDB)?

**Comment by myhussien** [comment]
@mcgibbon I'm also trying to figure this out. Did you manage to find anything?

**Comment by mcgibbon** [comment]
No, I wasn't able to solve the problem. I ended up running it without parallelism.

**Comment by maxpumperla** [comment]
@mcgibbon @myhussien sorry, this one slipped my attention. I've never used hyperas with mongodb, but it's doomed to fail. hyperas writes a temp file that the mongodb workers have to have access to. In principle that can work, but hyperas (as of now) isn't built for it.

**Comment by myhussien** [comment]
@maxpumperla Thanks for the info. I was going crazy trying to get it running. Is it possible you show us an example of how to do this with Hyperopt? I don't mind how messy it looks.

Thanks!
-M

**Comment by JonnoFTW** [comment]
I got it to work by commenting out the lines in optim.py that removed temp_model.py. From there I:

* specified an absolute path to my data file in data() 
* Set my trials to:  `trials = mongoexp.MongoTrials('mongo://localhost:27017/jobs/jobs', exp_key='htm_113_108')`
* set `$PYTHONPATH` to include my project directory containing `temp_model.py`
* Ran the worker script with: `./hyperopt-mongo-worker --mongo=localhost:27017/jobs --exp-key=htm_113_108`

**Comment by JonnoFTW** [comment]
@maxpumperla is there any chance of getting an extra argument in `optim.minimize` to keep `temp.py`? It's probably the simplest fix given my advice above. You'd just need to wrap the `os.remove` calls in an `if not keep_temp`.

**Comment by maxpumperla** [comment]
good point. seems like you could submit a PR, but I can do that as well.
