### ISSUE TITLE
temp_model.py import problem

### ISSUE THREAD

**Issue by huseynlilkin** [maxpumperla/hyperas#107]
Hello @maxpumperla ,

This is an awesome lib, thanks! When I try to run it a code a problem with temp_model.py. It doesn't import my functions/classses/scripts and have problem with "as" (when I use import `numpy as np` I got  `np is not defined` error, after deleting as np part, it worked )

Thanks in advance.

**Comment by huseynlilkin** [comment]
I've solved it after searching examples and install from master, thanks

**Comment by maxpumperla** [comment]
good to hear, I'll release a new version soon to prevent this sort of error. thanks
