### ISSUE TITLE
TypeError: 'Sequential' object is not iterable

### ISSUE THREAD

**Issue by mrgloom** [maxpumperla/hyperas#108]
I'm using linear model on  MNIST dataset searching for optimal regularization parameters.

```
>>> Imports:
#coding=utf-8

try:
    import keras
except:
    pass

try:
    from keras import regularizers
except:
    pass

try:
    from keras.models import Sequential
except:
    pass

try:
    from keras.layers import Dense, Dropout, Activation
except:
    pass

try:
    import numpy as np
except:
    pass

try:
    import pandas as pd
except:
    pass

try:
    from sklearn.model_selection import train_test_split
except:
    pass

try:
    from hyperas.distributions import uniform
except:
    pass

try:
    from hyperopt import STATUS_OK
except:
    pass

try:
    from hyperopt import tpe
except:
    pass

try:
    from hyperopt import Trials
except:
    pass

try:
    from hyperas import optim
except:
    pass

>>> Hyperas search space:

def get_space():
    return {
        'l2': hp.uniform('l2', 0, 1),
        'l2_1': hp.uniform('l2_1', 0, 1),
    }

>>> Data
  1: 
  2: train_data = np.genfromtxt('MNIST/train.csv', delimiter=',', skip_header=1)
  3: X= train_data[:,1:]
  4: y= train_data[:,0]
  5: 
  6: X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.20, random_state=42)
  7: 
  8: 
  9: 
 10: 
>>> Resulting replaced keras model:

  1: def keras_fmin_fnct(space):
  2: 
  3: 	w=28
  4: 	h=28
  5: 	input_shape = (w*h,)
  6: 	model = Sequential()
  7: 
  8: 	model.add(Dense(10, init='uniform', activation='softmax',
  9: 		kernel_regularizer=regularizers.l2(space['l2']),
 10: 		activity_regularizer=regularizers.l1(space['l2_1']),
 11: 		input_shape=input_shape))
 12: 		
 13: 	model.compile(loss=keras.losses.categorical_crossentropy,
 14: 				optimizer=keras.optimizers.Adadelta(),
 15: 				metrics=['accuracy'])
 16: 	
 17: 	#print(model.summary())
 18: 	
 19: 	return model
 20: 
/home/user/deep_learning/data3/temp_model.py:83: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(10, activation="softmax", kernel_regularizer=<keras.reg..., activity_regularizer=<keras.reg..., input_shape=(784,), kernel_initializer="uniform")`
Traceback (most recent call last):
  File "mnist_hyperas_linear.py", line 108, in <module>
    trials=Trials())
  File "/home/user/deep_learning/data3/anaconda3/lib/python3.6/site-packages/hyperas/optim.py", line 67, in minimize
    verbose=verbose)
  File "/home/user/deep_learning/data3/anaconda3/lib/python3.6/site-packages/hyperas/optim.py", line 133, in base_minimizer
    return_argmin=True),
  File "/home/user/deep_learning/data3/anaconda3/lib/python3.6/site-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/home/user/deep_learning/data3/anaconda3/lib/python3.6/site-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/home/user/deep_learning/data3/anaconda3/lib/python3.6/site-packages/hyperopt/fmin.py", line 320, in fmin
    rval.exhaust()
  File "/home/user/deep_learning/data3/anaconda3/lib/python3.6/site-packages/hyperopt/fmin.py", line 199, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/home/user/deep_learning/data3/anaconda3/lib/python3.6/site-packages/hyperopt/fmin.py", line 173, in run
    self.serial_evaluate()
  File "/home/user/deep_learning/data3/anaconda3/lib/python3.6/site-packages/hyperopt/fmin.py", line 92, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/home/user/deep_learning/data3/anaconda3/lib/python3.6/site-packages/hyperopt/base.py", line 845, in evaluate
    dict_rval = dict(rval)
TypeError: 'Sequential' object is not iterable
```

**Comment by mrgloom** [comment]
If it matters

~~~
Name: hyperas
Version: 0.4

Name: Keras
Version: 2.0.5

Name: tensorflow-gpu
Version: 1.2.1

Python 3.6.1

~~~

**Comment by pkainz** [comment]
Your model wrapper function needs to return a `dict`, e.g. 
```python
return {'loss': -acc, 'status': STATUS_OK, 'model': model}
```
You are returning the model instead.

**Comment by mrgloom** [comment]
yes, it was dumb mistake.

**Comment by ashutoshmishra1014** [comment]
from hyperopt import Trials, STATUS_OK, tpe
from hyperas import optim
from hyperas.distributions import choice, uniform, conditional
from keras.applications.inception_v3 import InceptionV3

def data():
    x_train = load_array('temp/X_train.bc')
    y_train = load_array('temp/Y_train.bc')
    x_val = load_array('temp/X_val.bc')
    y_val = load_array('temp/Y_val.bc')

    return x_train, y_train, x_val, y_val

def opt_model(x_train, y_train, x_val, y_val):
    base_model = InceptionV3(include_top=False, weights='imagenet', input_shape=(224, 224, 3))

    top_model = Sequential()
    top_model.add(Flatten(input_shape=base_model.layers[172].output_shape[1:]))

    if conditional({{choice(['two', 'three'])}}) == 'three':
        top_model.add(Dense(1024, activation='relu'))

    top_model.add(Dense({{choice([128, 256, 512])}}, activation={{choice(['relu', 'sigmoid'])}}))
    top_model.add(Dropout({{uniform(0, 1)}}))
    top_model.add(Dense(3, activation='softmax'))
    model = Model(inputs=base_model.input, outputs=top_model(base_model.layers[172].output))

    for l in model.layers[172]:
        l.trainable = False

    model.compile(optimizer={{choice(['rmsprop', 'adam', 'sgd'])}}, loss='categorical_crossentropy',
                  metrics=['accuracy'])

    model.fit(x_train, y_train,
              batch_size={{choice([8, 16, 32])}},
              epochs=1,
              verbose=2,
              validation_data=(x_val, y_val))
    score, acc = model.evaluate(x_val, y_val, verbose=0)
    print('Validation accuracy:', acc)

    return {'loss': -acc, 'status': STATUS_OK, 'model': model}



if __name__ == '__main__':
    best_run, best_model = optim.minimize(model=opt_model, data=data, algo=tpe.suggest, max_evals=5, trials=Trials())
    x_train, y_train, x_val, y_val = data()
    print("Evalutation of best performing model:")
    print(best_model.evaluate(x_val, y_val))
    print("Best performing model chosen hyper-parameters:")
    print(best_run)

Error:
  File "/home/ashutosh/Documents/Playground/_ve_/local/lib/python2.7/site-packages/hyperopt/base.py", line 840, in evaluate
    rval = self.fn(pyll_rval)
  File "/home/ashutosh/Documents/Playground/_ve_/botsupply/Projects/Danfoss/with-3d/temp_model.py", line 127, in keras_fmin_fnct
TypeError: **'Sequential' object is not iterable**

Hello @maxpumperla , request you to please help me out with the above issue.
Why do I get the error about the Sequential object for this program while for others Sequential model works just fine.
