### ISSUE TITLE
can I put the import outside of the functions? 

### ISSUE THREAD

**Issue by fluency03** [maxpumperla/hyperas#11]
As shown [here](https://github.com/maxpumperla/hyperas/blob/master/examples/lstm.py), why we have to put the import into the functions?

**Comment by maxpumperla** [comment]
The reason is that these functions (data/model) get serialized and read back from file. In the current implementation, if you don't have the imports in place, python won't find elements in your name space. 

I wanted to change this for a long time, though, so I'll work on a fix for this soon. Thanks!

**Comment by fluency03** [comment]
is there any way that I can avoid?

**Comment by maxpumperla** [comment]
I'll fix it soon! For now just put the imports into the function. Ugly, but it doesn't hurt. :)

**Comment by fluency03** [comment]
I am still confused why _python won't find elements in your name space._? Can you explain more? Thanks.

**Comment by maxpumperla** [comment]
Sure. Both data & model function are stored into files - by pure string manipulation. To ```import``` these functions again you need all relevant import statements right there.  E.g. if 
```{python}
def example():
    import foo
    foo.bar()
```
is put into a file, it reads
```
import foo
foo.bar()
```
If the import statement is missing, python will complain it doesn't find ```foo```.

**Comment by fluency03** [comment]
But why in normal cases, you can put `import` outside of a function, even though we still import this function?

**Comment by maxpumperla** [comment]
Sure, but this is not a "normal case". As I tried to indicate above, hyperas takes the *content* of the function and writes it to a file. If the import statement is not included in the function, then it's simply not available (as it's not in the file). This is a current *design choice of hyperas and really nothing deep*. 

The way to fix this is to *inspect* the script you're executing and extracting all imports. I'll have to see if that's possible. Thanks for your feedback in any case.

**Comment by fluency03** [comment]
Ok. I got it. The reason is behind how hyperas works. hyperas actually only takes every function into account when evaluating them not a whole program.  Thanks.

**Comment by maxpumperla** [comment]
Hey @fluency03, I finally got around to solving this issue. You can now use imports properly, i.e. the way you would everywhere else. I will release a new version soon, for now you can work on master.

**Comment by fluency03** [comment]
That's great! Thanks!

**Comment by fluency03** [comment]
@maxpumperla Can I update it by doing this: `sudo pip install git+https://github.com/maxpumperla/hyperas.git --upgrade --no-deps` ?

**Comment by maxpumperla** [comment]
That should do, I personally prefer cloning the repo, cd to it and do ```python setup.py install```. This way you can test and play with your own, local version.

**Comment by maxpumperla** [comment]
Alright, you should now be able to upgrade to version 0.2 via pip. Thanks for reporting this issue!
