### ISSUE TITLE
NameError: global name 'X_train' is not defined

### ISSUE THREAD

**Issue by drorhilman** [maxpumperla/hyperas#113]
I am trying to optimize the architecture of a simple network with hyperas...
The code for the get_model function:

```
def get_model_for_optim(x_train, y_train, x_test, y_test):

    n_layers = {{choice([1, 2, 4, 8])}}
    layer_width = {{choice([100, 200, 400])}}
    bottleneck_width = {{choice([10, 20, 40])}}
    dropout_rate = {{uniform(0, 1)}}
    learning_rate = {{uniform(0.000002, 0.001)}}
    
    inp_size = 50    
    inputs = Input(shape=(inp_size,), )
    x = Dense(layer_width, activation='relu')(inputs)
    for i in range(n_layers): 
        x = BatchNormalization()(x)   
        x = Dense(layer_width, activation='relu')(x)
        x = Dropout(dropout_rate)(x)

    x = Dense(bottleneck_width, activation='relu')(x)

    predictions = Dense(1, kernel_initializer='normal', activation='relu')(x)
    model = Model(inputs=inputs, outputs=predictions)
    model.compile(loss='mean_squared_error', optimizer=Adam(lr=learning_rate))

    model.fit(x_train, y_train,
              batch_size=128,
              epochs=3000,
              verbose=0,
              validation_data=(x_test, y_test),
              callbacks=[EarlyStopping(patience=200)])

    score = model.evaluate(x_test, y_test, verbose=0)
    return {'loss': score, 'status': STATUS_OK, 'model': model}
```

When trying to optimize it with hypers...

`best_run, best_model = optim.minimize(model=get_model_for_optim, algo=tpe.suggest, max_evals=200, trials=Trials(), data=get_data)`

I am getting an error...

> ** in keras_fmin_fnct
> NameError: global name 'x_train' is not defined**

how to solve this ? where is the error is coming from?

**Comment by maxpumperla** [comment]
@drorhilman can you put your full example in a gist or so? This usually happens if you don't put `x_train` in the data providing function, but I can't tell for sure without the code.

**Comment by shadiakiki1986** [comment]
Just a small rephrase: The parameters `x_train, y_train, x_test, y_test` are supposed to be returned by the data providing function. In the readme example, they're the return from `def data(): ...`

**Comment by achrafelz** [comment]
I always have this error after executing the following code : 
NameError: name 'x_train' is not defined 

def load_data(root, vfold_ratio=0.2, max_items_per_class= 5000 ):
    all_files = glob.glob(os.path.join(root, '*.npy'))

    #initialize variables 
    x = np.empty([0, 784])
    y = np.empty([0])
    class_names = []

    #load a subset of the data to memory 
    for idx, file in enumerate(all_files):
        data = np.load(file)
        data = data[0: max_items_per_class, :]
        labels = np.full(data.shape[0], idx)

        x = np.concatenate((x, data), axis=0)
        y = np.append(y, labels)

        class_name, ext = os.path.splitext(os.path.basename(file))
        class_names.append(class_name)

    data = None
    labels = None

    #separate into training and testing 
    permutation = np.random.permutation(y.shape[0])
    x = x[permutation, :]
    y = y[permutation]

    vfold_size = int(x.shape[0]/100*(vfold_ratio*100))

    x_test = x[0:vfold_size, :]
    y_test = y[0:vfold_size]

    x_train = x[vfold_size:x.shape[0], :]
    y_train = y[vfold_size:y.shape[0]]
    return x_train, y_train, x_test, y_test, class_names
  
At this point, everything is pretty okey but after I execute the next following code I get the error :

# Reshape and normalize
x_train = x_train.reshape(x_train.shape[0], image_size, image_size, 1).astype('float32')
x_test = x_test.reshape(x_test.shape[0], image_size, image_size, 1).astype('float32')

x_train /= 255.0
x_test /= 255.0

# Convert class vectors to class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)



NameError                                 Traceback (most recent call last)

<ipython-input-61-544c8e031aba> in <module>()
----> 1 x_train = x_train.reshape(x_train.shape[0], image_size, image_size, 1).astype('float32')
      2 x_test = x_test.reshape(x_test.shape[0], image_size, image_size, 1).astype('float32')
      3 
      4 x_train /= 255.0
      5 x_test /= 255.0

NameError: name 'x_train' is not defined

**Comment by shadiakiki1986** [comment]
@achrafelz can you provide your code where you call `optim.minimize(...)` ?

**Comment by achrafelz** [comment]
import os
import glob
import numpy as np
from tensorflow.keras import layers
from tensorflow import keras
import tensorflow as tf


def load_data(root, vfold_ratio=0.2, max_items_per_class= 4000 ):

    all_files = glob.glob(os.path.join(root, '*.npy'))



    #initialize variables

    x = np.empty([0, 784])

    y = np.empty([0])

    class_names = []



    #load each data file

    for idx, file in enumerate(all_files):

        data = np.load(file)

        data = data[0: max_items_per_class, :]

        labels = np.full(data.shape[0], idx)



        x = np.concatenate((x, data), axis=0)

        y = np.append(y, labels)



        class_name, ext = os.path.splitext(os.path.basename(file))

        class_names.append(class_name)



    data = None

    labels = None



    #randomize the dataset

    permutation = np.random.permutation(y.shape[0])

    x = x[permutation, :]

    y = y[permutation]



    #separate into training and testing

    vfold_size = int(x.shape[0]/100*(vfold_ratio*100))



    x_test = x[0:vfold_size, :]

    y_test = y[0:vfold_size]



    x_train = x[vfold_size:x.shape[0], :]

    y_train = y[vfold_size:y.shape[0]]

    return x_train, y_train, x_test, y_test, class_names



#Resolve the error (x_train is not defined)

x_train, y_train, x_test, y_test, class_names = load_data('data')

num_classes = len(class_names)

image_size = 28



print(len(x_train))


import matplotlib.pyplot as plt

from random import randint

%matplotlib inline

idx = randint(0, len(x_train))

plt.imshow(x_train[idx].reshape(28,28))

print(class_names[int(y_train[idx].item())])




Now it works, I haven’t  loaded my data first that is why x_train was always indicated as non-defined variable

De : Shadi Akiki [mailto:notifications@github.com]
Envoyé : vendredi 12 avril 2019 12:24
À : maxpumperla/hyperas
Cc : Achraf El-Ayadi; Mention
Objet : Re: [maxpumperla/hyperas] NameError: global name 'X_train' is not defined (#113)


@achrafelz<https://github.com/achrafelz> can you provide your code where you call optim.minimize(...) ?

**Comment by achrafelz** [comment]
import os
import glob
import numpy as np
from tensorflow.keras import layers
from tensorflow import keras 
import tensorflow as tf

def load_data(root, vfold_ratio=0.2, max_items_per_class= 4000 ):
    all_files = glob.glob(os.path.join(root, '*.npy'))

    #initialize variables 
    x = np.empty([0, 784])
    y = np.empty([0])
    class_names = []

    #load each data file 
    for idx, file in enumerate(all_files):
        data = np.load(file)
        data = data[0: max_items_per_class, :]
        labels = np.full(data.shape[0], idx)

        x = np.concatenate((x, data), axis=0)
        y = np.append(y, labels)

        class_name, ext = os.path.splitext(os.path.basename(file))
        class_names.append(class_name)

    data = None
    labels = None
    
    #randomize the dataset 
    permutation = np.random.permutation(y.shape[0])
    x = x[permutation, :]
    y = y[permutation]

    #separate into training and testing 
    vfold_size = int(x.shape[0]/100*(vfold_ratio*100))

    x_test = x[0:vfold_size, :]
    y_test = y[0:vfold_size]

    x_train = x[vfold_size:x.shape[0], :]
    y_train = y[vfold_size:y.shape[0]]
    return x_train, y_train, x_test, y_test, class_names

#Resolve the error (x_train is not defined)
x_train, y_train, x_test, y_test, class_names = load_data('data')  
num_classes = len(class_names)
image_size = 28

print(len(x_train))

import matplotlib.pyplot as plt
from random import randint
%matplotlib inline  
idx = randint(0, len(x_train))
plt.imshow(x_train[idx].reshape(28,28)) 
print(class_names[int(y_train[idx].item())])




Now it works, I haven’t  loaded my data first that is why x_train was always indicated as non-defined variable

**Comment by shadiakiki1986** [comment]
Good to hear that.
