### ISSUE TITLE
TypeError: require string label

### ISSUE THREAD

**Issue by gufengxiaoyuehan** [maxpumperla/hyperas#114]
when flowing the example code  [https://github.com/maxpumperla/hyperas](https://github.com/maxpumperla/hyperas) I get this.

no solution found after search.

###################
`sys.version
'3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]'
`

**Comment by shadiakiki1986** [comment]
Duplicate of #118 ?
