### ISSUE TITLE
Best hyperparameters reported are not members of get_space()

### ISSUE THREAD

**Issue by beaunorgeot** [maxpumperla/hyperas#116]
Thanks for all the work!

When running the lstm.py example, the best hyperparameters reported are not options within the script. For example, lstm.py has` batch_size={{choice([32, 64, 128])}}` but returns things like `'batch_size': 1`.  I'm not sure if this is a print bug or something deeper.

This seems to only be true for all {{choice[]}} arguments, not with uniform() arguments. 

![image](https://user-images.githubusercontent.com/9386672/29951546-3c159e66-8e78-11e7-951e-c1d488f2adff.png)

![image](https://user-images.githubusercontent.com/9386672/29951558-51bcd8a6-8e78-11e7-8ce3-fad013a37afe.png)

**Comment by lyakaap** [comment]
Returns is index of array. So you got the best value of batchsize=64.
If you would like to get the best value directly, use 'space_eval()'

**Comment by beaunorgeot** [comment]
thanks for quick reply @lyakaap! Could you please provide a snippet for the use of space_eval()?

**Comment by lyakaap** [comment]
https://jaberg.github.io/hyperopt/

**Comment by beaunorgeot** [comment]
Thank you again @lyakaap , this is super convenient.
