### ISSUE TITLE
TypeError: require string label

### ISSUE THREAD

**Issue by kaushalshetty** [maxpumperla/hyperas#118]
```
input_tensor = Input(shape=(2001,))
Dense({{choice([256,512,1024])}})(input_tensor)
```
choice is not working. Getting the below error for the above code.

`TypeError: require string label`

**Comment by shadiakiki1986** [comment]
You can't execute this code directly in python. You need to wrap your code in a `def model(...): ...` function, and then call it from `optim.minimize(model=create_model,...` like in the example in the readme.

The reason for this is that the way hyperas works is by doing template replacement of everything in the `{{...}}` into a separate temporary file, and then running the model with the replaced braces.
