### ISSUE TITLE
The results of `lstm` example: batch_size=1. 

### ISSUE THREAD

**Issue by fluency03** [maxpumperla/hyperas#12]
I have run [this](https://github.com/maxpumperla/hyperas/blob/master/examples/lstm.py) example and the results I got is:

    {'Dropout': 0.055013664364538806, 'batch_size': 1}

However, the `batch_size=1` is not even in the options: `batch_size={{choice([32, 64, 128])}}`.  Do you think this is reasonable?

**Comment by maxpumperla** [comment]
That's perfectly reasonable, as hyperopt ```choice``` returns the index of the dictionary to choose from.

**Comment by fluency03** [comment]
Ok, that means it is `32` of `[32, 64, 128]`.    I thought `1` is just the value instead of index. Thanks.

**Comment by fluency03** [comment]
Ok, that means `batch_size` is `32` of `[32, 64, 128]`?

**Comment by maxpumperla** [comment]
Hyperas returns the best model and the best parameters for you, so you can confirm your guess! :)

**Comment by fluency03** [comment]
since the 1 is index, is that the index of a list, which is with index starting from 0?  Then the result will be 64 in this case.

**Comment by maxpumperla** [comment]
It's the index of the dictionary, which in python start with 0. So, yes, 64 is the correct answer.
