### ISSUE TITLE
possible to optimize parameters for functional API models? 

### ISSUE THREAD

**Issue by qqqqqqq007** [maxpumperla/hyperas#120]
Hyperas run well on sequential models, but I need to optimize the parameters for multi-input models and models with shared weights using functional api. Could anyone help? Thank you very much!

**Comment by onion1003** [comment]
Hi,qqqqqqq007, you can see this issue[https://github.com/maxpumperla/hyperas/issues/119](url),then you can find hyperas is OK for functional API models.Just take care of the function ` data()`'s return's name must be equal to models input name,or it will be a not defined error

**Comment by maxpumperla** [comment]
https://github.com/maxpumperla/hyperas/blob/master/tests/test_functional_api.py

added a test recently, this was in fact always possible.
