### ISSUE TITLE
Pass arbitrary arguments to data and model function via optim.minimize

### ISSUE THREAD

**Issue by pciazynski** [maxpumperla/hyperas#122]
Hi! Thank you for amazing library :)

I have a question: It is possible to pass some arguments into `model` and `data` functions via `optim.minimize`? 

E.g. I want to pass path from command line to `data` function. I have access to command line arguments only in `__main__`, but I don't know if it possible to pass this into `data` function?

It could be like that:
```python
some_variable = '/some/path'
another_variable = 10
best_run, best_model = optim.minimize(model=model, data=data, algo=tpe.suggest, max_evals=3, trials=Trials(), arguments_for_data = [some_variable, another_variable])
```

**Comment by renan-ms** [comment]
Did you manage to pass arguments to data() function? I am gettting this error:
TypeError: minimize() got an unexpected keyword argument 'arguments_for_data'
