### ISSUE TITLE
TypeError: 'map' object is not subscriptable

### ISSUE THREAD

**Issue by YangBain** [maxpumperla/hyperas#124]
Traceback (most recent call last):
  File "train.caltech.py", line 40, in <module>
    image_paths_train = np.hstack(list(map(lambda one_class: one_class[:-10], image_paths_per_label)))
  File "train.caltech.py", line 40, in <lambda>
    image_paths_train = np.hstack(list(map(lambda one_class: one_class[:-10], image_paths_per_label)))
TypeError: 'map' object is not subscriptable

Who know the reason, Thank you very much.

**Comment by maxpumperla** [comment]
@YangBain this is an error in your code, not hyperas ;) apart from the fact that you can just google this (!), this indicates you're using python3, in which `map` works differently than in python2. usually wrapping in a `list` helps, but I see you did that. apart from that I can't help you any further given the info you provided.

**Comment by my1347** [comment]
@YangBain do you fix it buddy? I encounter the same issue
