### ISSUE TITLE
Passing data-manipulation script inside data() function

### ISSUE THREAD

**Issue by ansrivas** [maxpumperla/hyperas#13]
Hi Max, 

Thanks for incorporating hyperopt + keras in your wonderful implementation.

I am curious about a function retrieve_data_string() in optim.py. 
Basically in data() function, user is expected to pass X_test, X_train, Y_test, Y_train but one can not write their data read and preprocess snippets because of line.strip().

For eg.

 ` 

    # remove constant columns, which have std = 0
    cols_to_remove = []
    for col in df.columns:
        if (df[col].std() == 0):
            colsToRemove.append(col)`

This would fail if written in data(). Since this is just a string manipulation this can be easily taken care of.

So, just wondering if you wanted this API to be restricted in order to get data from a different module or pre-processing can be allowed in data() as well ?

**Comment by maxpumperla** [comment]
Hi Ankur,

Thank you, that's a very good point. That is clearly a bug and I'll have to fix that. I have another project in the pipeline, but can turn back to hyperas soon.

**Comment by maxpumperla** [comment]
Hey @ansrivas, I've done a quick test on my side. It should work on master now. Can you confirm?

**Comment by ansrivas** [comment]
Hi Max, 

Verified, thanks it works now. 
Will close this.
