### ISSUE TITLE
What's the point of `conditional` ?

### ISSUE THREAD

**Issue by shadiakiki1986** [maxpumperla/hyperas#130]
So `conditional` is just a function that passes its input. What's the point of it?

**Comment by jruivo-dev** [comment]
Hey,  did anyone figure out what's 'conditional' for?
My intuition is, 'conditional' is used to include or exclude a block of code from the network, is that it?

**Comment by maxpumperla** [comment]
`conditional` was meant as visual clue and at some point far back was needed for hyperas to correctly parse your source code. I'm removing it with https://github.com/maxpumperla/hyperas/pull/174
