### ISSUE TITLE
Error using hyperas

### ISSUE THREAD

**Issue by reversemartell** [maxpumperla/hyperas#135]
Hello! I get an error when i used the examples in github(https://github.com/maxpumperla/hyperas/tree/master/examples). I'm using w10 64 bits, Anaconda 3,Spyder 3.1.4, python 3.6.

Example : "cnn_lstm.py".
Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-1-1933c0fc7242>", line 69, in <module>
    trials=Trials())

  File "C:\Users\Miguel\Anaconda3\lib\site-packages\hyperas\optim.py", line 67, in minimize
    verbose=verbose)

  File "C:\Users\Miguel\Anaconda3\lib\site-packages\hyperas\optim.py", line 96, in base_minimizer
    model_str = get_hyperopt_model_string(model, data, functions, notebook_name, verbose, stack)

  File "C:\Users\Miguel\Anaconda3\lib\site-packages\hyperas\optim.py", line 178, in get_hyperopt_model_string
    with open(calling_script_file, 'r') as f:

OSError: [Errno 22] Invalid argument: 'C:\\Users\\Miguel\\<ipython-input-1-1933c0fc7242>'

**Comment by aprasla0922** [comment]
Hello. Did you ever get this resolved? I am having the same problem and difficulty localizing the solution.

**Comment by aprasla0922** [comment]
I found the solution to this problem.

When running on an iPython Notebook (like Jupyter), you need to specify the file name in the .minimize method. 

My code when from being:

```
best_run, best_model = optim.minimize(model = create_model,
                                     data = get_data,
                                     algo = tpe.suggest,
                                     max_evals = 10,
                                     trials = Trials)
```

to 
best_run, best_model = optim.minimize(model = create_model,
                                     data = get_data,
                                     algo = tpe.suggest,
                                     max_evals = 10,
                                     trials = Trials,
                                     notebook_name='From Scratch')#enter your notebook name here
