### ISSUE TITLE
hyperas in keras

### ISSUE THREAD

**Issue by zhangyu2ustc** [maxpumperla/hyperas#138]
Hi, I am using hyperas with Keras in python3 and got the following errors. Can anyone help? thanks!

Hyperas search space:

def get_space():
    return {
        'Conv2D': hp.choice('Conv2D', [32,64]),
        'Conv2D_1': hp.choice('Conv2D_1', [32,64]),
        'Dense': hp.choice('Dense', [64,128,256]),
    }

>>> Data
  1: 
  2: (X_train,y_train),(X_test,y_test) = mnist.load_data()
  3: X_train = np.float32(X_train)/255
  4: X_test = np.float32(X_test)/255
  5: 
  6: nsamples,img_rows,img_cols = X_train.shape
  7: nb_class = len(np.unique(y_train))
  8: if K.image_data_format() == 'channels_first':
  9:     img_shape = (1,img_rows,img_cols)
 10: elif K.image_data_format() == 'channels_last':
 11:     img_shape = (img_rows,img_cols,1)
 12: 
 13: X_train = X_train.reshape((X_train.shape[0],)+img_shape)
 14: X_test = X_test.reshape((X_test.shape[0],)+img_shape)
 15: Y_train = np_utils.to_categorical(y_train,nb_class)
 16: Y_test = np_utils.to_categorical(y_test,nb_class)
 17: 
 18: 
 19: 
 20: 
>>> Resulting replaced keras model:

   1: def keras_fmin_fnct(space):
   2: 
   3:     nsamples,img_rows,img_cols = X_train.shape
   4:     nb_class = len(np.unique(y_train))
   5:     if K.image_data_format() == 'channels_first':
   6:         img_shape = (1,img_rows,img_cols)
   7:     elif K.image_data_format() == 'channels_last':
   8:         img_shape = (img_rows,img_cols,1)
   9:         
  10:     #input_shape = np.append(np.array([None]),list(img_shape))
  11:     model = Sequential()
  12:     model.add(Conv2D( space['Conv2D'], (convsize,convsize), padding='same', activation='relu',input_shape=img_shape))
  13:     model.add(Conv2D( space['Conv2D_1'], (convsize,convsize), padding='same', activation='relu'))
  14:     model.add(MaxPooling2D((poolsize,poolsize)))
  15:     model.add(Dropout(0.2))
  16:         
  17:     model.add(Flatten())
  18:     model.add(Dense(space['Dense'],activation='relu'))
  19:     model.add(Dropout(0.5))
  20:     model.add(Dense(nb_class,activation='softmax'))
  21:     
  22:     model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
  23:     model.summary()
  24:     
  25:     model_history = model.fit(X_train,Y_train,batch_size=128,epochs=10,validation_split=0.05)
  26:     scores = model.evaluate(X_test,Y_test)
  27:     print(scores)
  28:     return {'scores':scores[0],'status':STATUS_OK,'model':model}
  29: 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-bd58f3db5b26> in <module>()
     63                                      max_evals = 5,
     64                                      trials = Trials(),
---> 65                                      notebook_name='tensorflow_practice_test5')
     66 print(best_model.evaluate(X_test,Y_test))
     67 print(best_run)

/mnt/home_sq/yzhang/python_venv/tensorflow/lib/python3.5/site-packages/hyperas/optim.py in minimize(model, data, algo, max_evals, trials, functions, rseed, notebook_name, verbose, eval_space, return_space)
     65                                      full_model_string=None,
     66                                      notebook_name=notebook_name,
---> 67                                      verbose=verbose)
     68 
     69     best_model = None

/mnt/home_sq/yzhang/python_venv/tensorflow/lib/python3.5/site-packages/hyperas/optim.py in base_minimizer(model, data, functions, algo, max_evals, trials, rseed, full_model_string, notebook_name, verbose, stack)
    126     return (
    127         fmin(keras_fmin_fnct,
--> 128              space=get_space(),
    129              algo=algo,
    130              max_evals=max_evals,

/mnt/home_sq/yzhang/pylearn/temp_model.py in get_space()

/mnt/home_sq/yzhang/python_venv/tensorflow/lib/python3.5/site-packages/hyperopt/pyll_utils.py in wrapper(label, *args, **kwargs)
     20         if not is_real_string and not is_literal_string:
     21             raise TypeError('require string label')
---> 22         return f(label, *args, **kwargs)
     23     return wrapper
     24 

TypeError: hp_choice() takes 2 positional arguments but 3 were given

**Comment by mingfeisun** [comment]
It seems that you pass one more parameter to the choice function, something like this:
`choice('label', [something1, something2, ..]`

If the 'label' is removed, then I think the TypeError will disappear, like this:
`choice([something1, something2, ...]`

I guess the label arg for hp_choice is automatically passed by hyperas, and the value is the name of corresponding layer. Hope this helps.

**Comment by maxpumperla** [comment]
@zhangyu2ustc yes, @mingfeisun  is exactly right. you need to move `'label'` out of `choice`.
