### ISSUE TITLE
Functional API not supported

### ISSUE THREAD

**Issue by GMarzinotto** [maxpumperla/hyperas#139]
Hello !

I have a quick question
Does Hyperas works on models built using the Functional API?
I have had a hard time trying to set it up without success

Kind regards,
Gabriel M

**Comment by maxpumperla** [comment]
@GMarzinotto can you send the example you're trying to use?

**Comment by bderose** [comment]
@GMarzinotto, yes! You can use the Keras functional API with hyperas. Can you share a minimal example of what you're working?

I had the same question while working with Keras 2.0.4 and the latest hyperas this afternoon but got things working just fine.
