### ISSUE TITLE
Bug when there are multiple hyper-parameter to tune in one layer

### ISSUE THREAD

**Issue by haoyangz** [maxpumperla/hyperas#14]
Thank you for the great work in combing hyperopt with keras!

I think I spotted a bug when you have more than one hyper-parameter to tune in one layer:

For example:
```
    model = Sequential()
    model.add(Convolution2D({{choice([32,64])}}, 1, {{choice([7,11,15])}}, border_mode='same', input_shape=(4, 1, 101),activation='relu'))
    model.add(MaxPooling2D(pool_size=(1, 2),strides=(1,2)))
    model.add(Convolution2D({{choice([64,128])}},1,3, border_mode='same',activation='relu'))
    model.add(MaxPooling2D(pool_size=(1, 2),strides=(1,2)))
    model.add(Flatten())
    model.add(Dense({{choice([32,64,128])}},activation='relu'))
    model.add(Dropout({{choice([0.1,0.5,0.7])}}))
    model.add(Dense(2,activation='softmax'))
```

Running on this model, it will output:
```
>>> Hyperas search space:

def get_space():
    return {
        'Convolution2D': hp.choice('Convolution2D', [32,64]),
        'Convolution2D_1': hp.choice('Convolution2D_1', [7,11,15]),
        'Dense': hp.choice('Dense', [64,128]),
        'Dropout': hp.choice('Dropout', [32,64,128]),
    }
```
which shows that the mapping from the parameter name to the value choices is messed up.

I assume this is a bug?

**Comment by maxpumperla** [comment]
Thanks, that's indeed a bug. I'll see how to fix this and get back to you. -M

**Comment by maxpumperla** [comment]
@haoyangz, I've found a solution for your bug, see an example here:

https://github.com/maxpumperla/hyperas/blob/master/examples/cnn_lstm.py

Note that the whole issue arises because in your example parameters weren't named with keywords. Most of the time I did that, and so didn't notice the issue. Anyway, should be fixed now. Thanks for reporting this!

**Comment by maxpumperla** [comment]
Version 0.2 is now released an contains the fix.
