### ISSUE TITLE
Can you use L1 and L2 regularization as well in regression problems?

### ISSUE THREAD

**Issue by Shuyib** [maxpumperla/hyperas#145]
Hi,

I used the datasets that come along with installing Keras such as the boston housing one using the code in the README file as a template. Instead of using Dropout i used L1 and L2 regularization. I get the following error after running on the terminal (Mac) with the command `nohup python test_boston_dataset_hyper.py &` see below. Otherwise, I'm using Python 3.5.2 , Keras 2.0.8, Tensorflow 1.3.0, Theano 0.9.0, hyperas 0.4.

```
Using TensorFlow backend.
>>> Imports:
#coding=utf-8

from __future__ import print_function

try:
    from hyperopt import Trials, STATUS_OK, tpe
except:
    pass

try:
    from keras.datasets import boston_housing
except:
    pass

try:
    from keras.layers.core import Dense, Dropout, Activation
except:
    pass

try:
    from keras.models import Sequential
except:
    pass

try:
    from keras.utils import np_utils
except:
    pass

try:
    from keras import regularizers
except:
    pass

try:
    import numpy as np
except:
    pass

try:
    from hyperas import optim
except:
    pass

try:
    from hyperas.distributions import choice, uniform, conditional
except:
    pass

>>> Hyperas search space:

def get_space():
    return {
        'Dense': hp.choice('Dense', [4, 16, 32, 64]),
        'l1_l2': hp.uniform('l1_l2', 0, 1),
        'l1_l2_1': hp.uniform('l1_l2_1', 0, 1),
        'Activation': hp.choice('Activation', ['relu', 'tanh', 'sigmoid']),
        'Dense_1': hp.choice('Dense_1', [4, 16, 32, 64]),
        'l1_l2_2': hp.uniform('l1_l2_2', 0, 1),
        'l1_l2_3': hp.uniform('l1_l2_3', 0, 1),
        'Activation_1': hp.choice('Activation_1', ['relu', 'tanh','sigmoid']),
        'optimizer': hp.choice('optimizer', ['rmsprop', 'adam', 'sgd']),
        'batch_size': hp.choice('batch_size', [64, 128]),
    }

>>> Data
  1: 
  2: '''loading data, scaling it and returning the data to be used throughout'''
  3: (x_train, y_train), (x_test, y_test) =  boston_housing.load_data()
  4: x_train = x_train.astype('float32')
  5: x_test = x_test.astype('float32')
  6: mean = x_train.mean(axis=0)
  7: x_train -= mean
  8: std = x_train.std(axis=0)
  9: x_train /= std
 10: x_test -= mean
 11: x_test /= std
 12: y_train = np.log(y_train)
 13: y_test = np.log(y_test)
 14: 
 15: 
 16: 
 17: 
 18: 
>>> Resulting replaced keras model:

   1: def keras_fmin_fnct(space):
   2: 
   3:     """
   4:     Model providing function:
   5: 
   6:     Create Keras model with double curly brackets dropped-in as needed.
   7:     Return value has to be a valid python dictionary with two customary keys:
   8:         - loss: Specify a numeric evaluation metric to be minimized
   9:         - status: Just use STATUS_OK and see hyperopt documentation if not feasible
  10:     The last one is optional, though recommended, namely:
  11:         - model: specify the model just created so that we can later use it again.
  12:     """
  13:     model = Sequential()
  14:     model.add(Dense(space['Dense'], kernel_regularizer = regularizers.l1_l2(
  15:     space['l1_l2'],space['l1_l2_1']),input_shape = (x_train.shape[1],)))
  16:     model.add(Activation(space['Activation']))
  17:     model.add(Dense(space['Dense_1'], regularizers.l1_l2(space['l1_l2_2'],
  18:     space['l1_l2_3'])))
  19:     model.add(Activation(space['Activation_1']))
  20:     model.add(Dense(1))
  21:     
  22:     model.compile(loss='mse', metrics=['mae'],
  23:                   optimizer=space['optimizer'])
  24: 
  25:     model.fit(x_train, y_train,
  26:               batch_size=space['batch_size'],
  27:               epochs=1,
  28:               verbose=2,
  29:               validation_data=(x_test, y_test))
  30:     val_mse, val_mae = model.evaluate(x_test, y_test, verbose=0)
  31:     print('Test mse:', val_mse)
  32:     return {'loss': -val_mse, 'status': STATUS_OK, 'model': model}
```
  33: 
Traceback (most recent call last):
  File "test_boston_housing.py", line 69, in <module>
    trials=Trials())
  File "/Users/../anaconda/envs/py35/lib/python3.5/site-packages/hyperas/optim.py", line 67, in minimize
    verbose=verbose)
  File "/Users/../anaconda/envs/py35/lib/python3.5/site-packages/hyperas/optim.py", line 133, in base_minimizer
    return_argmin=True),
  File "/Users/../anaconda/envs/py35/lib/python3.5/site-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/Users/../anaconda/envs/py35/lib/python3.5/site-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/Users/../anaconda/envs/py35/lib/python3.5/site-packages/hyperopt/fmin.py", line 320, in fmin
    rval.exhaust()
  File "/Users/../anaconda/envs/py35/lib/python3.5/site-packages/hyperopt/fmin.py", line 199, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/Users/../anaconda/envs/py35/lib/python3.5/site-packages/hyperopt/fmin.py", line 173, in run
    self.serial_evaluate()
  File "/Users/../anaconda/envs/py35/lib/python3.5/site-packages/hyperopt/fmin.py", line 92, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/Users/../anaconda/envs/py35/lib/python3.5/site-packages/hyperopt/base.py", line 840, in evaluate
    rval = self.fn(pyll_rval)
  File "/Users/../Desktop/temp_model.py", line 85, in keras_fmin_fnct
  File "/Users/../anaconda/envs/py35/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 42, in wrapper
    str(list(args[1:])))
TypeError: `Dense` can accept only 1 positional arguments ('units',), but you passed the following positional arguments: [32, <keras.regularizers.L1L2 object at 0x11b74aba8>]

**Comment by maxpumperla** [comment]
@Shuyib  it complains because in your second Dense layer with regularization (line 17 above) you're missing the `kernel_regularizer` argument you have in line 14. If you don't provide key-words to your keras models this won't work, even without hyperas.

**Comment by Shuyib** [comment]
Thanks @maxpumperla
