### ISSUE TITLE
TypeError: 'generator' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by tchaton** [maxpumperla/hyperas#146]
Using TensorFlow backend.
>>> Imports:
#coding=utf-8

from __future__ import print_function

try:
    from hyperopt import Trials, STATUS_OK, tpe
except:
    pass

try:
    from hyperas import optim
except:
    pass

try:
    from hyperas.distributions import choice, uniform, conditional
except:
    pass

try:
    from keras.models import Sequential
except:
    pass

try:
    from keras.layers.core import Dense, Dropout, Activation
except:
    pass

try:
    from keras.datasets import mnist
except:
    pass

try:
    from keras.utils import np_utils
except:
    pass

>>> Hyperas search space:

def get_space():
    return {
        'Dropout': hp.uniform('Dropout', 0, 1),
        'Dense': hp.choice('Dense', [256, 512, 1024]),
        'Activation': hp.choice('Activation', ['relu', 'sigmoid']),
        'Dropout_1': hp.uniform('Dropout_1', 0, 1),
        'conditional': hp.choice('conditional', ['three', 'four']),
        'add': hp.choice('add', [Dropout(0.5), Activation('linear')]),
        'optimizer': hp.choice('optimizer', ['rmsprop', 'adam', 'sgd']),
        'batch_size': hp.choice('batch_size', [64, 128]),
    }

>>> Data
  1: 
  2: '''
  3: Data providing function:
  4: 
  5: This function is separated from model() so that hyperopt
  6: won't reload data for each evaluation run.
  7: '''
  8: (X_train, y_train), (X_test, y_test) = mnist.load_data()
  9: X_train = X_train.reshape(60000, 784)
 10: X_test = X_test.reshape(10000, 784)
 11: X_train = X_train.astype('float32')
 12: X_test = X_test.astype('float32')
 13: X_train /= 255
 14: X_test /= 255
 15: nb_classes = 10
 16: Y_train = np_utils.to_categorical(y_train, nb_classes)
 17: Y_test = np_utils.to_categorical(y_test, nb_classes)
 18: 
 19: 
 20: 
>>> Resulting replaced keras model:

   1: def keras_fmin_fnct(space):
   2: 
   3:     '''
   4:     Model providing function:
   5: 
   6:     Create Keras model with double curly brackets dropped-in as needed.
   7:     Return value has to be a valid python dictionary with two customary keys:
   8:         - loss: Specify a numeric evaluation metric to be minimized
   9:         - status: Just use STATUS_OK and see hyperopt documentation if not feasible
  10:     The last one is optional, though recommended, namely:
  11:         - model: specify the model just created so that we can later use it again.
  12:     '''
  13:     model = Sequential()
  14:     model.add(Dense(512, input_shape=(784,)))
  15:     model.add(Activation('relu'))
  16:     model.add(Dropout(space['Dropout']))
  17:     model.add(Dense(space['Dense']))
  18:     model.add(Activation(space['Activation']))
  19:     model.add(Dropout(space['Dropout_1']))
  20: 
  21:     # If we choose 'four', add an additional fourth layer
  22:     if conditional(space['conditional']) == 'four':
  23:         model.add(Dense(100))
  24:         model.add(space['add'])
  25:         model.add(Activation('relu'))
  26: 
  27:     model.add(Dense(10))
  28:     model.add(Activation('softmax'))
  29: 
  30:     model.compile(loss='categorical_crossentropy',
  31:                   optimizer=space['optimizer'],
  32:                   metrics=['accuracy'])
  33: 
  34:     model.fit(X_train, Y_train,
  35:               batch_size=space['batch_size'],
  36:               nb_epoch=1,
  37:               verbose=2,
  38:               validation_data=(X_test, Y_test))
  39:     score, acc = model.evaluate(X_test, Y_test, verbose=0)
  40:     print('Test accuracy:', acc)
  41:     return {'loss': -acc, 'status': STATUS_OK, 'model': model}
  42: 
Traceback (most recent call last):
  File "complex.py", line 77, in <module>
    trials=Trials())
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 67, in minimize
    verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 136, in base_minimizer
    return_argmin=True),
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/base.py", line 786, in __init__
    pyll.toposort(self.expr)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/pyll/base.py", line 715, in toposort
    assert order[-1] == expr
TypeError: 'generator' object has no attribute '__getitem__'

**Comment by maxpumperla** [comment]
that's that: https://github.com/hyperopt/hyperopt/issues/357
