### ISSUE TITLE
When data can't fit into memory at once

### ISSUE THREAD

**Issue by haoyangz** [maxpumperla/hyperas#15]
The example given in README demonstrates the usage of hyperas when you have a rather small dataset that you can load into memory at once. I wonder if there is any chance that it can take a "generator" as input, like [fit_generator](http://keras.io/getting-started/faq/#how-can-i-use-keras-with-datasets-that-dont-fit-in-memory) in Keras?

**Comment by maxpumperla** [comment]
That should be possible in principle, sure, but I'll have to check the details and provide an example. Let me get back to you.

Note that this can get very expensive really quickly, so you might think about sampling data and having a few more epochs thrown in instead.

**Comment by maxpumperla** [comment]
Here's one example, with this you should be good to go:

https://github.com/maxpumperla/hyperas/blob/master/examples/cifar_generator_cnn.py

**Comment by Miail** [comment]
this is an incorrect use of generator.. it seems like you load all the data points into ram, which not the purpose with fit_generator.
