### ISSUE TITLE
Is search space path fixed every time?

### ISSUE THREAD

**Issue by Kirayue** [maxpumperla/hyperas#154]
Hi, @maxpumperla 

I outputted the trials and found that 
`t = Trials()`
`best_run, model = optim.minimize( model=create_model,  data=data, algo=tpe.suggest, max_evals=15, trials=t, verbose=False)`
`for trial in t.trials:`                                         
`     print(trial['misc']['vals'])`

I got the same search space order after I changed the data split. Is this normal? 

![2018-03-05 12 18 51](https://user-images.githubusercontent.com/13309212/36957507-c398526e-206f-11e8-8e6a-f953efac9027.jpg)

![2018-03-05 12 18 58](https://user-images.githubusercontent.com/13309212/36957514-cd91e938-206f-11e8-890e-300e12cf5fc6.jpg)

Because this is related to my research, it is very important to me. 

And thank you for this awesome repo.

**Comment by maxpumperla** [comment]
@Kirayue you need to set the seed for hyperopt, not only for your data split. Note that with TPE you get a few fixed trials per random seed every time (if I recall correctly 20), before it starts exploring.

**Comment by Kirayue** [comment]
@maxpumperla 
Thanks for your reply. I saw the differences after setting max_evals to 30. 

Thanks again.
