### ISSUE TITLE
The fundamentals of your template parsing code

### ISSUE THREAD

**Issue by ryanpeach** [maxpumperla/hyperas#156]
Hi there,

I really love this projects template methodology and hyperopt's use of distributions within the template. However, for some complex reasons, I can not use hyperopt for my project. As such, I would like to fork this project and make it have a "general purpose backend" to where you can use any arbitrary hyper parameter optimizer with basically the same syntax as this project touts. I have identified that the main imports from hyperopt are the distributions (which I intend to replace with simple lambdas) and then the following:

fmin, tpe, hp, STATUS_OK, Trials, space_eval

These all have complex IO and are often passing objects around, I wonder if you could guide me to the core of *your* code, particularly the template and string handling.

Thanks!

**Comment by maxpumperla** [comment]
hey @ryanpeach, hyperas is a really small project. All the code your interested in is in:

https://github.com/maxpumperla/hyperas/blob/master/hyperas/optim.py

and 

https://github.com/maxpumperla/hyperas/blob/master/hyperas/utils.py

all we do is parse the template and translate it into proper hyperopt by reconstructing the `space` object that's passed to `fmin`. If you want to do the same for a different engine, say spearmint, you'll have to write something similar to `optim.py` for that particular tool.
