### ISSUE TITLE
How to handle '#'

### ISSUE THREAD

**Issue by shashwattrivedi** [maxpumperla/hyperas#162]
```
def remove_hashtag(text):
    if text[0]=='#':
        return '<hashtag>'
    else:
        return text
```
I have to handle '#' in twitter data, but when I use 
```
best_run, best_model = optim.minimize(model=model_for_hyperas,
                                          data=data,
                                          algo=tpe.suggest,
                                          max_evals=5,
                                          trials=Trials()
                                     ,notebook_name='<notebook_name>',)
```
It shows me error
File "<unknown>", line 120
    if text[0]=='
                 ^
SyntaxError: EOL while scanning string literal

How to handle this

**Comment by Dahlasam** [comment]
have you tried to introduce your custom function through 'functions'-paramter in the minimize-call?

So for example
def remove_hashtag(text):
    if text[0]=='#':
        return '<hashtag>'
    else:
        return text

funcs = [remove_hashtag]

best_run, best_model = optim.minimize(model=model_for_hyperas,
                                          data=data,
                                          algo=tpe.suggest,
                                          max_evals=5,
                                          functions=funcs,
                                          trials=Trials()
                                     ,notebook_name='<notebook_name>')

This enables you to call 'remove_hashtag(...)' from the 'create_model' function for example.
Is this something you are looking for?

**Comment by maxpumperla** [comment]
@shashwattrivedi any feed back on this? what @Dahlasam should work.

**Comment by shashwattrivedi** [comment]
Actually, I handled it by changing the utils.py code a little bit...
the line which removes comments to

`string = re.sub(re.compile("(?<!'|\")#.*\n"), "\n", string)  # remove #...\n comments`

It worked for me, I didn't try the @Dahlasam's suggestion
