### ISSUE TITLE
Can I use it just with ipython?

### ISSUE THREAD

**Issue by loraince** [maxpumperla/hyperas#164]
I tried with win10 systems. It worked in a Jupyter notebook. However, it showed OSError in ipython with [Errno 22] Invalid argument: 'C:\\\\mywork\\\\< ipython-input-3-76977dd2255e>'
Then, I tried with linux. My linux doesn't has a GUI so I can't run Jupyter notebook. When I tried the code in ipython, it showed:  FileNotFoundError: [Errno 2] No such file or directory: '/home/lxun/< ipython-input-4-545da7bd6a57 >'
Does it mean this tool can only work with Jupyter notebook?

**Comment by loraince** [comment]
Well, now I use .py script and it works.  The problems above happened when I was running code in console.

**Comment by maxpumperla** [comment]
yes, only jupyter notebooks, no ipython support I'm afraid. (this is on the readme I think).

**Comment by adammenges** [comment]
For what it's worth I see this error in jupyterlab
