### ISSUE TITLE
Can I save the intermediate models and weights in different files?

### ISSUE THREAD

**Issue by LeZhengThu** [maxpumperla/hyperas#166]
I can use a ModelCheckpoint to save the intermediate models and weights, but the optim funtion will overwrite it with the latest trial. But I want to save the intermediate model and weights for every trial. How can I do this? Thanks.

**Comment by maxpumperla** [comment]
@LeZhengThu in the return statement of the model providing function you can essentially register anything you want.

```python
return {'loss': -accuracy, 'status': STATUS_OK, 'model': model, 'ckpts': <YOUR_CALLBACK>}
```

something like this would do, but be aware that this will require a ton of memory, as this object keeps growing.

**Comment by LeZhengThu** [comment]
@maxpumperla Thanks for the reply. I want to save the model weights of every trial in different files, like "weights_trial_0", "weights_trial_1", and so on. So in the create_model function, how to get the id of the current trial?

**Comment by PawelFaron** [comment]
> @maxpumperla Thanks for the reply. I want to save the model weights of every trial in different files, like "weights_trial_0", "weights_trial_1", and so on. So in the create_model function, how to get the id of the current trial?

    model_name = f'{model.name}'
    index_search = re.search('model_(\d+)', model_name, re.IGNORECASE)
    model_suffix = "_" + index_search.group(1) if index_search else ""
    best_model_path = os.path.join("models", model_name + ".hdf5")
    monitor = 'val_auc' + model_suffix
    mcp_save = ModelCheckpoint(filepath=best_model_path, save_best_only=True, monitor=monitor, mode='max')
