### ISSUE TITLE
Questions about nb_epoch and some configurations of `optim.minimize`

### ISSUE THREAD

**Issue by fluency03** [maxpumperla/hyperas#17]
Hi @maxpumperla !

I saw that all of the examples provided are with `nb_epoch=1`. I am wondering that: 
1. Will I get more reasonable results (more optimal hyper-parameters) if I set `nb_epoch` larger than 1 since it will do the optimization by over many times of epochs? 
2. In the method `optim.minimize` there are some parameters I would like to discuss:
- `algo`: what are the options of this parameter (like `tpe.suggest` and `rand.suggest`)? And what are your suggestions about when should we choose which, especially for RNN/LSTM model? 
- `max_evals`: this is the maximum number of execution of `evaluate`. I am wondering the difference between the following two settings: (1)`nb_epoch=10` and `max_evals=1`; (2) `nb_epoch=1` and `max_evals=10`. 
- `trials`: I have seen `Trials()`. What is this parameter used for?

Thanks.

**Comment by maxpumperla** [comment]
1. One epoch was chosen to make the examples run quickly. Of course you get more reliable results with more epochs. Ideally, if you can afford it computationally, use *the same setup* as for regular training. In practice, you'll see it's often a trade-off for speed.
2. TPE is more sophisticated and should in general yield better results, but random search is surprisingly good in practice. Check out this for more.
https://papers.nips.cc/paper/4443-algorithms-for-hyper-parameter-optimization.pdf
```max_evals``` is for the number of optimization runs and completely independent of ```nb_epoch```, i.e. 1)nb_epoch=10 and max_evals=1 is just one trial and 2) nb_epoch=1 and max_evals=10 is ten trials for optim. Which brings us to: ```Trials()```, which will store information on each optimization run. For more on core ```hyperopt``` data structures, you should really have a look at https://github.com/hyperopt/hyperopt/wiki
