### ISSUE TITLE
Attempting to use uninitialized value Adam/lr

### ISSUE THREAD

**Issue by jhmenke** [maxpumperla/hyperas#170]
Hello,

when trying to adapt hyperas to my problem, an unusual error appears:

> Traceback (most recent call last):
>   File "C:/Users/Jan/Desktop/PytorchSpeedTest/WindowsTest/hyperastest.py", line 64, in <module>
>     best_run, best_model = optim.minimize(model=create_model, data=data, algo=tpe.suggest, max_evals=5, trials=Trials())
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\hyperas\optim.py", line 67, in minimize
>     verbose=verbose)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\hyperas\optim.py", line 133, in base_minimizer
>     return_argmin=True),
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 307, in fmin
>     return_argmin=return_argmin,
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\hyperopt\base.py", line 635, in fmin
>     return_argmin=return_argmin)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 320, in fmin
>     rval.exhaust()
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 199, in exhaust
>     self.run(self.max_evals - n_done, block_until_done=self.async)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 173, in run
>     self.serial_evaluate()
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\hyperopt\fmin.py", line 92, in serial_evaluate
>     result = self.domain.evaluate(spec, ctrl)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\hyperopt\base.py", line 840, in evaluate
>     rval = self.fn(pyll_rval)
>   File "C:\Users\Jan\Desktop\PytorchSpeedTest\WindowsTest\temp_model.py", line 93, in keras_fmin_fnct
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\keras\models.py", line 1002, in fit
>     validation_steps=validation_steps)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\keras\engine\training.py", line 1705, in fit
>     validation_steps=validation_steps)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\keras\engine\training.py", line 1256, in _fit_loop
>     callbacks.on_epoch_end(epoch, epoch_logs)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\keras\callbacks.py", line 77, in on_epoch_end
>     callback.on_epoch_end(epoch, logs)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\callbacks.py", line 905, in on_epoch_end
>     logs['lr'] = K.get_value(self.model.optimizer.lr)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\backend.py", line 2632, in get_value
>     return x.eval(session=get_session())
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 552, in eval
>     return self._variable.eval(session=session)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 710, in eval
>     return _eval_using_default_session(self, feed_dict, self.graph, session)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 5180, in _eval_using_default_session
>     return session.run(tensors, feed_dict)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
>     run_metadata_ptr)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
>     run_metadata)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Adam/lr
> 	 [[Node: _retval_Adam/lr_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Adam/lr)]]

Did anyone encounter this before? I tried different optimizers, all with the same result.
My create_model function is pretty barebones at the moment:

```
def create_model(x_train, y_train, x_test, y_test, x_validate, y_validate):
    model = Sequential()
    model.add(Dense(44, input_shape=(22,)))
    model.add(Activation({{choice(['relu', 'sigmoid'])}}))
    model.add(Dense(44))
    model.add(Activation({{choice(['relu', 'sigmoid'])}}))
    model.add(Dense(15))

    model.compile(loss='mae', metrics=['mse'], optimizer="adam")

    es = EarlyStopping(monitor='val_loss', min_delta=1e-5, patience=10)
    rlr = ReduceLROnPlateau(factor=0.1, patience=10)
    _ = model.fit(x_train, y_train, epochs=150, verbose=0, callbacks=[es, rlr],
                  batch_size=24, validation_data=(x_validate, y_validate))

    mae, mse = model.evaluate(x_test, y_test, verbose=0)
    print('MAE:', mae)
    return {'loss': mae, 'status': STATUS_OK, 'model': model}
```

**Comment by jhmenke** [comment]
After debugging, this is actually an issue with keras ReduceLROnPlateau, i'm making another issue on this.

**Comment by Tempest6** [comment]
> After debugging, this is actually an issue with keras ReduceLROnPlateau, i'm making another issue on this.

 i am facing the same problem .can you tell more about how to fix it?

**Comment by scindew** [comment]
Me too. The problem comes when I use ReduceLROnPlateau. Does anyone know the solution?
