### ISSUE TITLE
Support for keras ReduceLROnPlateau

### ISSUE THREAD

**Issue by jhmenke** [maxpumperla/hyperas#171]
If i add the ReduceLROnPlateau callback of keras into my create_model function, it results in the following error:

> Traceback (most recent call last):
>[...]
>     return session.run(tensors, feed_dict)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
>     run_metadata_ptr)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
>     run_metadata)
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Adam/lr
> 	 [[Node: _retval_Adam/lr_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Adam/lr)]]

Did anyone encounter this before? I tried different optimizers, all with the same result.
My create_model function is pretty barebones at the moment:

```
def create_model(x_train, y_train, x_test, y_test, x_validate, y_validate):
    model = Sequential()
    model.add(Dense(44, input_shape=(22,)))
    model.add(Activation({{choice(['relu', 'sigmoid'])}}))
    model.add(Dense(44))
    model.add(Activation({{choice(['relu', 'sigmoid'])}}))
    model.add(Dense(15))

    model.compile(loss='mae', metrics=['mse'], optimizer="adam")

    es = EarlyStopping(monitor='val_loss', min_delta=1e-5, patience=10)
    rlr = ReduceLROnPlateau(factor=0.1, patience=10)
    _ = model.fit(x_train, y_train, epochs=150, verbose=0, callbacks=[es, rlr],
                  batch_size=24, validation_data=(x_validate, y_validate))

    mae, mse = model.evaluate(x_test, y_test, verbose=0)
    print('MAE:', mae)
    return {'loss': mae, 'status': STATUS_OK, 'model': model}
```

**Comment by maxpumperla** [comment]
I don't see any problems with this, just added a test. CI is passing as well. 

https://github.com/maxpumperla/hyperas/blob/d8ecbd2fd01c7726c842878c5b0f83fc66c07f59/tests/test_lr_plateau.py#L40-L42

**Comment by scindew** [comment]
I have the same issue with ReduceLROnPlateau. Did you solve it?

**Comment by jhmenke** [comment]
> I have the same issue with ReduceLROnPlateau. Did you solve it?

sorry, i can't remember if i solved or used a different library
