### ISSUE TITLE
TypeError: 'generator' object is not subscriptable for the example code

### ISSUE THREAD

**Issue by DLMLPYRTRAINING** [maxpumperla/hyperas#179]
I am trying to run the example given in the readme and getting an error:

Please help.

Output and Error stack:
`C:\Users\SKL\AppData\Local\Programs\Python\Python36\python.exe C:/Users/SKL/Documents/DLMLPYRTRAINING/Day6/mnist_keras_model_save_and_reload_with_hp.py
C:\Users\SKL\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
>>> Imports:
#coding=utf-8

from __future__ import print_function

try:
    import keras
except:
    pass

try:
    from keras.datasets import mnist
except:
    pass

try:
    from keras.models import Sequential, model_from_json
except:
    pass

try:
    from keras.layers import Dense, Dropout, Activation
except:
    pass

try:
    from keras.optimizers import RMSprop
except:
    pass

try:
    from keras.utils import np_utils
except:
    pass

try:
    from hyperopt import Trials, STATUS_OK, tpe
except:
    pass

try:
    from hyperas import optim
except:
    pass

try:
    from hyperas.distributions import choice, uniform, conditional
except:
    pass

try:
    import datetime, os
except:
    pass

try:
    from matplotlib import pyplot as plt
except:
    pass

try:
    from random import randint
except:
    pass

try:
    import numpy as np
except:
    pass

try:
    from PIL import Image, ImageOps
except:
    pass

>>> Hyperas search space:

def get_space():
    return {
        'Dropout': hp.uniform('Dropout', 0, 1),
        'Dense': hp.choice('Dense', [256, 512, 1024]),
        'Activation': hp.choice('Activation', ['relu', 'sigmoid']),
        'Dropout_1': hp.uniform('Dropout_1', 0, 1),
        'conditional': hp.choice('conditional', ['three', 'four']),
        'add': hp.choice('add', [Dropout(0.5), Activation('linear')]),
        'optimizer': hp.choice('optimizer', ['rmsprop', 'adam', 'sgd']),
        'batch_size': hp.choice('batch_size', [64, 128]),
    }

>>> Data
  1: 
  2: """
  3: Data providing function:
  4: 
  5: This function is separated from model() so that hyperopt
  6: won't reload data for each evaluation run.
  7: """
  8: (x_train, y_train), (x_test, y_test) = mnist.load_data()
  9: x_train = x_train.reshape(60000, 784)
 10: x_test = x_test.reshape(10000, 784)
 11: x_train = x_train.astype('float32')
 12: x_test = x_test.astype('float32')
 13: x_train /= 255
 14: x_test /= 255
 15: nb_classes = 10
 16: y_train = np_utils.to_categorical(y_train, nb_classes)
 17: y_test = np_utils.to_categorical(y_test, nb_classes)
 18: 
 19: 
 20: 
>>> Resulting replaced keras model:

   1: def keras_fmin_fnct(space):
   2: 
   3:     """
   4:     Model providing function:
   5: 
   6:     Create Keras model with double curly brackets dropped-in as needed.
   7:     Return value has to be a valid python dictionary with two customary keys:
   8:         - loss: Specify a numeric evaluation metric to be minimized
   9:         - status: Just use STATUS_OK and see hyperopt documentation if not feasible
  10:     The last one is optional, though recommended, namely:
  11:         - model: specify the model just created so that we can later use it again.
  12:     """
  13:     model = Sequential()
  14:     model.add(Dense(512, input_shape=(784,)))
  15:     model.add(Activation('relu'))
  16:     model.add(Dropout(space['Dropout']))
  17:     model.add(Dense(space['Dense']))
  18:     model.add(Activation(space['Activation']))
  19:     model.add(Dropout(space['Dropout_1']))
  20: 
  21:     # If we choose 'four', add an additional fourth layer
  22:     if conditional(space['conditional']) == 'four':
  23:         model.add(Dense(100))
  24: 
  25:         # We can also choose between complete sets of layers
  26: 
  27:         model.add(space['add'])
  28:         model.add(Activation('relu'))
  29: 
  30:     model.add(Dense(10))
  31:     model.add(Activation('softmax'))
  32: 
  33:     model.compile(loss='categorical_crossentropy', metrics=['accuracy'],
  34:                   optimizer=space['optimizer'])
  35: 
  36:     model.fit(x_train, y_train,
  37:               batch_size=space['batch_size'],
  38:               epochs=20,
  39:               verbose=2,
  40:               validation_data=(x_test, y_test))
  41:     score, acc = model.evaluate(x_test, y_test, verbose=0)
  42:     print('Test accuracy:', acc)
  43:     return {'loss': -acc, 'status': STATUS_OK, 'model': model}
  44: 
Traceback (most recent call last):
  File "C:/Users/SKL/Documents/DLMLPYRTRAINING/Day6/mnist_keras_model_save_and_reload_with_hp.py", line 109, in <module>
    trials=Trials())
  File "C:\Users\SKL\AppData\Local\Programs\Python\Python36\lib\site-packages\hyperas\optim.py", line 67, in minimize
    verbose=verbose)
  File "C:\Users\SKL\AppData\Local\Programs\Python\Python36\lib\site-packages\hyperas\optim.py", line 133, in base_minimizer
    return_argmin=True),
  File "C:\Users\SKL\AppData\Local\Programs\Python\Python36\lib\site-packages\hyperopt\fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "C:\Users\SKL\AppData\Local\Programs\Python\Python36\lib\site-packages\hyperopt\base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "C:\Users\SKL\AppData\Local\Programs\Python\Python36\lib\site-packages\hyperopt\fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)
  File "C:\Users\SKL\AppData\Local\Programs\Python\Python36\lib\site-packages\hyperopt\base.py", line 786, in __init__
    pyll.toposort(self.expr)
  File "C:\Users\SKL\AppData\Local\Programs\Python\Python36\lib\site-packages\hyperopt\pyll\base.py", line 715, in toposort
    assert order[-1] == expr
TypeError: 'generator' object is not subscriptable

Process finished with exit code 1
`

**Comment by DLMLPYRTRAINING** [comment]
Literally copy-pasted the code from the example : using pycharm by the way.
https://raw.githubusercontent.com/maxpumperla/hyperas/master/examples/mnist_readme.py

**Comment by DLMLPYRTRAINING** [comment]
Ok found the solution and this is a duplicate ticket, please close it.

https://github.com/maxpumperla/hyperas/issues/125

**Comment by manikantamaka** [comment]
from flask import Flask, render_template, request, redirect, url_for
from joblib import load
from twitter_scraper import get_tweets

from get_tweets import get_related_tweets

pipeline = load("C:/Users/MANIKANTA/Downloads/Hate-Speech-Classification-deployed-using-Flask-master/Hate-Speech-Classification-deployed-using-Flask-master/text_classification_twitterAnalysis.joblib")


def requestResults(name):
    tweets = get_tweets(name)
    tweets['prediction'] = pipeline.predict(tweets['tweet_text'])
    data = str(tweets.prediction.value_counts()) + '\n\n'
    return data + str(tweets)


app = Flask(__name__)


@app.route('/')
def home():
    return render_template('home.html')


@app.route('/', methods=['POST', 'GET'])
def get_data():
    if request.method == 'POST':
        user = request.form['search']
        return redirect(url_for('success', name=user))


@app.route('/success/<name>')
def success(name):
    return "<xmp>" + str(requestResults(name)) + " </xmp> "


if __name__ == '__main__' :
    app.run(debug=True)
-------------------------------------------------------------------------
File "C:\anaconda1\lib\site-packages\flask\app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "C:\anaconda1\lib\site-packages\flask\app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "C:\anaconda1\lib\site-packages\flask\app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\anaconda1\lib\site-packages\flask\_compat.py", line 35, in reraise
raise value
File "C:\anaconda1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "C:\anaconda1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\anaconda1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\anaconda1\lib\site-packages\flask\_compat.py", line 35, in reraise
raise value
File "C:\anaconda1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "C:\anaconda1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Users\MANIKANTA\Downloads\Hate-Speech-Classification-deployed-using-Flask-master\Hate-Speech-Classification-deployed-using-Flask-master\get_sentiment.py", line 34, in success
return "<xmp>" + str(requestResults(name)) + " </xmp> "
File "C:\Users\MANIKANTA\Downloads\Hate-Speech-Classification-deployed-using-Flask-master\Hate-Speech-Classification-deployed-using-Flask-master\get_sentiment.py", line 12, in requestResults
tweets['prediction'] = pipeline.predict(tweets['tweet_text'])
TypeError: 'generator' object is not subscriptable
