### ISSUE TITLE
temp_model.py invalid syntax error

### ISSUE THREAD

**Issue by kirtov** [maxpumperla/hyperas#18]
Hello @maxpumperla !
I am using ipython notebooks
I have a syntax error by running your example code on my data. It is because of generated `temp-model.py` file. Especially because of first line of this file, which contains some comments and placed without any spec. simbols, like # or '''

There are first lines of temp_model.py file.

> importers when locating support scripts as well as when importing modules.
> import sys
> import importlib.machinery # importlib first so we can test #15386 via -m
> import importlib.util
> import types
> from pkgutil import read_code, get_importer

There is a syntax error in my main .py file

> File "PATH_TO/temp_model.py", line 1
>     importers when locating support scripts as well as when importing modules.
>                  ^
> SyntaxError: invalid syntax

Whats going wrong? Thanks for helping!

**Comment by maxpumperla** [comment]
What happened?

**Comment by kirtov** [comment]
It was problem with ipython notebook. If I will use .py then all is good.

But now I have another problem with hyperopt and hyperopt-sklearn compability (I think)

> Traceback (most recent call last):
  File "hyperas_test.py", line 61, in <module>
    trials=Trials())
  File "/home/kkochetov/myenv/lib/python3.4/site-packages/hyperas/optim.py", line 31, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)
  File "/home/kkochetov/myenv/lib/python3.4/site-packages/hyperas/optim.py", line 110, in base_minimizer
    trials=trials)
  File "/home/kkochetov/myenv/hyperopt/build/lib/hyperopt/fmin.py", line 306, in fmin
    return_argmin=return_argmin,
  File "/home/kkochetov/myenv/hyperopt/build/lib/hyperopt/base.py", line 625, in fmin
    return fmin_module.fmin(
AttributeError: 'function' object has no attribute 'fmin'

**Comment by kirtov** [comment]
Ok, I solved this problem as described here by Ghost. https://github.com/hyperopt/hyperopt/issues/234

**Comment by MrWanter** [comment]
Hi!  kirtov,
I have run the example code properly, but I came across the problem with invalid syntax of `temp_model.py` when I ran my own code edited from the example,  I don't use IPython notebook, I just run the script by 'python my_code/untitled.py', then it raise the error info as follows:
```
Unexpected error: <type 'exceptions.SyntaxError'>
Traceback (most recent call last):
  File "untitled.py", line 216, in <module>
    trials=Trials())
  File "c:\scisoft\winpython-64bit-2.7.9.4\python-2.7.9.amd64\hyperas-\hyperas\o
ptim.py", line 31, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)
  File "c:\scisoft\winpython-64bit-2.7.9.4\python-2.7.9.amd64\hyperas-\hyperas\o
ptim.py", line 96, in base_minimizer
    from temp_model import keras_fmin_fnct, get_space
  File "C:\SciSoft\my_code\temp_model.py", line 11
    Make sure to have every relevant import statement included here and return d
ata as
            ^
SyntaxError: invalid syntax
```
I'm wondering if you can help me and give me some advice, thanks in advance.

**Comment by vibhabs** [comment]
C:\Users\vibha bs\Desktop\pycodes>python vibha.py
  File "vibha.py", line 1
    Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
           ^
SyntaxError: invalid syntax
