### ISSUE TITLE
Errors running the example in Native Spyder 

### ISSUE THREAD

**Issue by raaju-shiv** [maxpumperla/hyperas#182]
I have been running you example code in my native Spyder, however, I keep getting error messages due to invalid path:
Here is the list of errors:

```
Traceback (most recent call last):

  File "<ipython-input-31-d89937937552>", line 6, in <module>
    trials=Trials())

  File "C:\Users\rajaramans2\AppData\Local\Continuum\anaconda3\lib\site-packages\hyperas\optim.py", line 67, in minimize
    verbose=verbose)

  File "C:\Users\rajaramans2\AppData\Local\Continuum\anaconda3\lib\site-packages\hyperas\optim.py", line 96, in base_minimizer
    model_str = get_hyperopt_model_string(model, data, functions, notebook_name, verbose, stack)

  File "C:\Users\rajaramans2\AppData\Local\Continuum\anaconda3\lib\site-packages\hyperas\optim.py", line 178, in get_hyperopt_model_string
    with open(calling_script_file, 'r') as f:

OSError: [Errno 22] Invalid argument: 'C:\\Users\\rajaramans2\\codes\\hyperas-master\\<ipython-input-31-d89937937552>'

```
The problem is in optim.py. Can you suggest how to resolve this issue? 

Before filing an issue, please make sure to tick the following boxes.

- [x] Make sure your issue hasn't been filed already. Use GitHub search or manually check the [existing issues](https://github.com/maxpumperla/hyperas/issues), also the closed ones. Also, make sure to check the FAQ section of our [readme](https://github.com/maxpumperla/hyperas/blob/master/README.md).

- [x] Install latest hyperas from GitHub:
pip install git+git://github.com/maxpumperla/hyperas.git

- [x] Install latest hyperopt from GitHub:
pip install git+git://github.com/hyperopt/hyperopt.git

- [x] We have continuous integration running with Travis and make sure the build stays "green". If, after installing test utilities with `pip install pytest pytest-cov pep8 pytest-pep8`, you can't successfully run `python -m pytest` there's very likely a problem on your side that should be addressed before creating an issue.

- [x] Create a gist containing your complete script, or a minimal version of it, that can be used to reproduce your issue. Also, add your _full stack trace_ to that gist. In many cases your error message is enough to at least give some guidance.

**Comment by maxpumperla** [comment]
https://github.com/maxpumperla/hyperas/issues/101

**Comment by maxpumperla** [comment]
duplicate. sorry, we don't support spyder and other IDEs
