### ISSUE TITLE
hyperopt  OsError

### ISSUE THREAD

**Issue by jesuisnicolasdavid** [maxpumperla/hyperas#2]
I have this error that i can't get rid of "OSError: [Errno 2] No such file or directory: './temp.pyc". My code is the same as the CNN_LSTM example from keras. But i am running from a virtualenv.

**Comment by jstypka** [comment]
I had the same one, probably you have a setting to not save `.pyc` files in the development environment. I put the line that deletes this file into a `try...except` statement and it worked. I can make a pull request with it if @maxpumperla  wants.

**Comment by maxpumperla** [comment]
Thanks @jstypka, as a matter of fact I will push exactly the same solution you propose in a few minutes (was busy the last days).

**Comment by maxpumperla** [comment]
OK, @jesuisnicolasdavid, a patch is available on master. I'll work on releasing a new version, but I want to find a solution to #3 first. So, if you want to use the latest version right now, clone the repo and do ```python setup.py install```. Thanks

**Comment by maxpumperla** [comment]
OK, new release is out. Can we close this?

**Comment by jesuisnicolasdavid** [comment]
Sure thanks!
