### ISSUE TITLE
Is Cross-Validation Possible?

### ISSUE THREAD

**Issue by redraven984** [maxpumperla/hyperas#200]
Before filing an issue, please make sure to tick the following boxes.

- [X] Make sure your issue hasn't been filed already. Use GitHub search or manually check the [existing issues](https://github.com/maxpumperla/hyperas/issues), also the closed ones. Also, make sure to check the FAQ section of our [readme](https://github.com/maxpumperla/hyperas/blob/master/README.md).

- [X] Install latest hyperas from GitHub:
pip install git+git://github.com/maxpumperla/hyperas.git

- [X] Install latest hyperopt from GitHub:
pip install git+git://github.com/hyperopt/hyperopt.git

- [X] We have continuous integration running with Travis and make sure the build stays "green". If, after installing test utilities with `pip install pytest pytest-cov pep8 pytest-pep8`, you can't successfully run `python -m pytest` there's very likely a problem on your side that should be addressed before creating an issue.

- [X] Create a gist containing your complete script, or a minimal version of it, that can be used to reproduce your issue. Also, add your _full stack trace_ to that gist. In many cases your error message is enough to at least give some guidance.

I have a question regarding cross-validation. The current hyperas will train parameters on a fixed set of data, but will not rotate the data sets (k-fold). Is this correct? We could of course manually force this by running K versions of hyperas script. This wouldn't be correct because we would have different parameters to reconcile at the end. Is there a way to do cross-validation in the current library? This is more to verify than to request a change. I want to make sure I'm not missing something before I try a more complex approach. Thanks!

**Comment by maxpumperla** [comment]
@redraven984 hyperas uses hyperopt under the hood, which will try to minimize a single metric for a given search space. All you need to do is pass in that metric. I don't see why you couldn't define your model once in the `model` function and then fit your model k times and average the loss (or whatever you have in mind) after that.

```
    return {'loss': -acc, 'status': STATUS_OK, 'model': model}
```

The syntax remains the same, but `acc` is something else in your case.
