### ISSUE TITLE
Regarding custom loss

### ISSUE THREAD

**Issue by BenLim88** [maxpumperla/hyperas#218]
How can I define custom loss functions in Hyperas?

I am running a 4 dense layers architecture with 3 outputs. For the loss, i would like to define it as:

Loss
 =
( (Output1 Error) / max[Output1_pred, Output1_true] ) +
( (Output2 Error) / max[Output2_pred, Output2_true] ) +
( (Output3 Error) / max[Output3_pred, Output3_true] )

**Comment by maxpumperla** [comment]
@BenLim88 not exactly sure what you mean, just define your loss and return it as `loss` in the return value of your `model` function here

https://github.com/maxpumperla/hyperas/blob/master/examples/simple.py#L65
