### ISSUE TITLE
Error with example

### ISSUE THREAD

**Issue by tkrishp** [maxpumperla/hyperas#22]
I run into this error when trying out the example provided in README. What can I do to fix it?

```
Traceback (most recent call last):
  File "grid_search.py", line 80, in <module>
    print(best_model.evaluate(X_test, Y_test))
AttributeError: 'NoneType' object has no attribute 'evaluate'
```

**Comment by maxpumperla** [comment]
Hi, could you please give me the complete example of yours? The error says that ```best_model``` is not actually a Keras model, but ```None```, suggesting you deviate in some way from the example.

**Comment by tkrishp** [comment]
I take it back; I just retried the example and this time it worked. I'll post if I run into any other issue.
