### ISSUE TITLE
Please give some paper or slices about the method, maybe how it works

### ISSUE THREAD

**Issue by HankerSia** [maxpumperla/hyperas#231]
I am using this tool, but I found little data about the principle, please give me some links or paper about how it works. Thank you very much!

**Comment by HankerSia** [comment]
is this one https://www.lri.fr/~kegl/research/PDFs/BeBaBeKe11.pdf?

**Comment by maxpumperla** [comment]
@HankerSia yeah, this one is a good starting point. James Bergstra is the author of hyperopt, the library that underpins this one. Have a look at what's going on there: https://github.com/hyperopt. Your best bet is to understand TPE .
