### ISSUE TITLE
Errors while running example files

### ISSUE THREAD

**Issue by laubonghaudoi** [maxpumperla/hyperas#26]
Hi @maxpumperla, I just install the latest 0.2 release of hyperas and tried to run the example files. I run the simple.py on both IPyhon and python console, both failed but different error messages. I first ran it on an IPython console, and here is the result:

> Unexpected error: <type 'exceptions.NameError'>
> Traceback (most recent call last):
> 
>   File "<ipython-input-1-8b529b655784>", line 1, in <module>
>     runfile('C:/Anaconda2/Lib/site-packages/hyperas-0.2/examples/simple.py', wdir='C:/Anaconda2/Lib/site-packages/hyperas-0.2/examples')
> 
>   File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
>     exec(compile(scripttext, filename, 'exec'), glob, loc)
> 
>   File "C:/Anaconda2/Lib/site-packages/hyperas-0.2/examples/simple.py", line 75, in <module>
>     trials=Trials())
> 
>   File "C:\Anaconda2\lib\site-packages\hyperas-0.2-py2.7.egg\hyperas\optim.py", line 31, in minimize
>     best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)
> 
>   File "C:\Anaconda2\lib\site-packages\hyperas-0.2-py2.7.egg\hyperas\optim.py", line 96, in base_minimizer
>     from temp_model import keras_fmin_fnct, get_space
> 
>   File "temp_model.py", line 23, in <module>
>     (X_train, y_train), (X_test, y_test) = mnist.load_data()
> 
> NameError: name 'mnist' is not defined

While I ran it on an normal python console, the output is:

> runfile('C:/Anaconda2/Lib/site-packages/hyperas-0.2/examples/simple.py', wdir='C:/Anaconda2/Lib/site-packages/hyperas-0.2/examples')
> Using Theano backend.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
>     execfile(filename, namespace)
>   File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
>     exec(compile(scripttext, filename, 'exec'), glob, loc)
>   File "C:/Anaconda2/Lib/site-packages/hyperas-0.2/examples/simple.py", line 75, in <module>
>     trials=Trials())
>   File "C:\Anaconda2\lib\site-packages\hyperas-0.2-py2.7.egg\hyperas\optim.py", line 31, in minimize
>     best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)
>   File "C:\Anaconda2\lib\site-packages\hyperas-0.2-py2.7.egg\hyperas\optim.py", line 92, in base_minimizer
>     model_str = get_hyperopt_model_string(model, data)
>   File "C:\Anaconda2\lib\site-packages\hyperas-0.2-py2.7.egg\hyperas\optim.py", line 66, in get_hyperopt_model_string
>     with open(calling_script_file, 'r') as f:
> IOError: [Errno 22] invalid mode ('r') or filename: 'C:\Anaconda2\Lib\site-packages\hyperas-0.2\examples\<stdin>'

How to solve this? I think I've installed all the dependencies, including the hyperopt. I also tried other examples like the lstm.py and mnist_ensemble.py and the same error occurs.

**Comment by maxpumperla** [comment]
@liubanghoudai24 looks like you're not using a recent version of keras, ```mnist``` as dataset (which is your error message) in this form wasn't available in earlier versions. It's def. not a hyperas issue.
