### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow' after hyperas installation 

### ISSUE THREAD

**Issue by floriancartuta** [maxpumperla/hyperas#268]
After I installed the hyperas through pip (pip install hyperas), I get the error: 

> ModuleNotFoundError: No module named 'tensorflow' for command: `from keras.models import Model, Sequential`
Below you can find the modules installed in the virtual environment.

Please advice how can I correct or revert.

> 
>  pip  freeze
> attrs==19.3.0
> backcall==0.1.0
> bleach==3.1.0
> cloudpickle==1.2.2
> cycler==0.10.0
> Cython==0.29.13
> decorator==4.4.1
> defusedxml==0.6.0
> entrypoints==0.3
> future==0.18.2
> h5py==2.10.0
> hyperas==0.4.1
> hyperopt==0.2.2
> importlib-metadata==1.3.0
> ipykernel==5.1.3
> ipython==7.11.1
> ipython-genutils==0.2.0
> ipywidgets==7.5.1
> jedi==0.15.2
> Jinja2==2.10.3
> joblib==0.14.0
> jsonschema==3.2.0
> jupyter==1.0.0
> jupyter-client==5.3.4
> jupyter-console==6.0.0
> jupyter-core==4.6.1
> Keras==2.3.1
> Keras-Applications==1.0.8
> Keras-Preprocessing==1.1.0
> kiwisolver==1.1.0
> llvmlite==0.30.0
> MarkupSafe==1.1.1
> matplotlib==3.1.1
> mistune==0.8.4
> more-itertools==8.0.2
> nbconvert==5.6.1
> nbformat==5.0.3
> networkx==2.2
> notebook==6.0.2
> numba==0.46.0
> numpy==1.17.3
> pandas==0.25.2
> pandocfilters==1.4.2
> parso==0.5.2
> patsy==0.5.1
> pexpect==4.7.0
> pickleshare==0.7.5
> prometheus-client==0.7.1
> prompt-toolkit==2.0.10
> ptyprocess==0.6.0
> Pygments==2.5.2
> pyod==0.7.5
> pyparsing==2.4.5
> pyramid-arima==0.9.0
> pyrsistent==0.15.6
> python-dateutil==2.8.0
> pytz==2019.3
> PyYAML==5.3
> pyzmq==18.1.1
> qtconsole==4.6.0
> scikit-learn==0.21.3
> scipy==1.3.1
> Send2Trash==1.5.0
> six==1.12.0
> statsmodels==0.10.1
> terminado==0.8.3
> testpath==0.4.4
> tornado==6.0.3
> tqdm==4.41.1
> traitlets==4.3.3
> wcwidth==0.1.8
> webencodings==0.5.1
> widgetsnbextension==3.5.1
> zipp==0.6.0
>

**Comment by JonnoFTW** [comment]
Have you tried installing tensorflow? Installation can be a little bit complicated if you aren't using conda and want to use the GPU.

**Comment by floriancartuta** [comment]
> e

Yes, I tried and solved the problem.

**Comment by floriancartuta** [comment]
Reinstalled tensorflow and problem is solved.
