### ISSUE TITLE
Hyperas in Keras (Older Version)

### ISSUE THREAD

**Issue by Riashat** [maxpumperla/hyperas#27]
I am using an older version of keras - last cloned around January/February.
I am trying to integrate hyperas with keras, and get an error as follows when building my keras model with dropout.

model.add(Dropout({{uniform(0, 1)}}))

File "/Library/Python/2.7/site-packages/hyperopt/pyll_utils.py", line 48, in hp_uniform
raise TypeError('require string label')
TypeError: require string label

Can someone please help me as to why I get an error like this? I am simply initially following the examples as in the hyperas examples.

**Comment by maxpumperla** [comment]
Hi @Riashat, sorry for responding so late. This issue fell off my radar. I'm not sure which version of Keras you're using, but I vaguely remember that the API for ```Dropout``` has undergone a change. So, if ```Dropout({{uniform(0, 1)}})``` doesn't work that would indicate ```Dropout(0.12)``` doesn't work. You need to use the templates to match API requirements. Does that make sense? I hope it's still useful to you. 

In any case, is there no way you can upgrade your keras version? Backward compatibility is a difficult thing to do and keras is moving fast.

**Comment by maxpumperla** [comment]
I'm really sorry, but I can't backward-support this. Did you manage to upgrade keras?

**Comment by nieoh** [comment]
@maxpumperla Doprout(0.12) works in newest version of keras but Doprout({{uniform(0, 1)}}) doesn't work.

**Comment by brannondorsey** [comment]
Any progress with this? I'm experiencing the same error with any `hyperas.distribution` that I use.

**Comment by ahmadammari** [comment]
same problem here
python v2.7.12 (Anaconda), hyperas v0.3, Keras v2.0.2

**Comment by verarim** [comment]
Getting a similar error

python v3.6.0 anaconda, Keras v2.0.2, hyperas v0.3 (not dev!)
 
model.add(LSTM(input_shape=(input_length, input_dim),
                   units={{choice([300, 200, 100])}},
                   activation = 'tanh',
                   recurrent_activation = 'hard_sigmoid',
                   return_sequences=True))

units={{choice([300, 200, 100])}},
File "/home/vera/anaconda3/lib/python3.6/site-packages/hyperopt/pyll_utils.py", line 21, in wrapper
    raise TypeError('require string label')

**Comment by maxpumperla** [comment]
@verarim please upgrade `hyperopt`

**Comment by verarim** [comment]
@maxpumperla I think I have it upgraded:
pip install --upgrade git+https://github.com/hyperopt/hyperopt.git
pip install --upgrade git+https://github.com/maxpumperla/hyperas.git

keras                     v2.0.2           
hyperas                   v0.3                
hyperopt                  v0.1                      

But the error of such kind remains:

model.add(Dropout({{uniform(0, 1)}}))
  File "/home/vera/anaconda3/lib/python3.6/site-packages/hyperopt/pyll_utils.py", line 21, in wrapper
    raise TypeError('require string label')
TypeError: require string label

**Comment by deepakgeorge** [comment]
I am facing the same issue with units={{choice([300, 200, 100])}} 

I am using latest version of the following packages from pip on python 3.5.3
keras, tensorflow,hyperopt,hyperas

Any updates?

**Comment by simeneide** [comment]
Hi @maxpumperla, any updates on this? I just installed hyperas on an ubuntu-box with pip. Then tried to do a choose or uniform with the same error as people above. Also tried to upgrade to github-master (by verarim's commands above) with no luck. It also failed similarly on a different machine.

hyperas (0.3)
hyperopt (0.1)
Keras (2.0.2) (and 2.0.3 in a different attempt)

**Comment by achigeor** [comment]
Same error here. Using:
python 2.7
keras v2.0.4
hyperas v0.3
hyperopt v0.1

File "/home/user/.virtualenvs/venv/local/lib/python2.7/site-packages/hyperopt/pyll_utils.py", line 21, in wrapper
    raise TypeError('require string label')
TypeError: require string label

**Comment by DaveGerson** [comment]
It's about a year on but I am also seeing this issue.  Has anybody found a way to resolve it yet?

**Comment by julyzamora** [comment]
I have the same issue as well :(

**Comment by shadiakiki1986** [comment]
Possible duplicate of #106. Check [my reply](https://github.com/maxpumperla/hyperas/issues/106#issuecomment-339894530) for future-comers
