### ISSUE TITLE
Reload data with every run

### ISSUE THREAD

**Issue by jstypka** [maxpumperla/hyperas#3]
In the example given, all the data has to be loaded and rebuilt before every trial which is quite a time-consuming task, especially for big datasets.

Is it possible to do it once in the beginning and reuse in all the runs?

**Comment by maxpumperla** [comment]
That is a very valid point, one that is bugging me a lot myself. As you have noticed, hyperas does what it does by string manipulation. This may not be ideal, but as of now I know no other way (that's quick). When you reload the "replaced" keras model from temp file, it just doesn't know what your X's and y's are. So this is just a problem with how python organizes their imports and namespaces (well, my problem). 

I'm fairly certain there has to be a way around, but right now I have no solution. Any ideas are highly welcome.

**Comment by maxpumperla** [comment]
Hey @jstypka, I've pushed an update to master. Your requirements are met, but now the API is slighty more complicated, but also somewhat cleaner. I think it's still worth it, though.

**Comment by maxpumperla** [comment]
Alright, version 0.0.2 is now on PyPI. Thanks again.

**Comment by jstypka** [comment]
Nice, that was quick! I think the API is more than fine, it's cleaner now as you say. The only thing I'm concerned with is that if you look at e.g. the `data()` as a mortal Python programmer it doesn't make any sense - it just fiddles with some data and quits without returning anything. And then in the `model` function suddenly you access `X_train` and `Y_train` variables out of the blue, which might be very confusing.

I think it should be good to at least explicitly mention that the variable names are important and that's how you transfer the data between functions (or maybe the `data` function could return anything). Because if you don't know that, the code is really confusing and, in fact, it took me a while to figure out why it even works and doesn't throw a syntax error :)

But thanks anyway, you sped up my code around 5 times probably with this change :)

**Comment by maxpumperla** [comment]
Cool, I'm happy to hear that. 

I share the same concerns as you. On top of what you say, this kind of thing can also lead to all sorts of uncontrollable side effects. What happens if I don't use it in a single script, but call it from somewhere else etc. 

So at least I should think of something creative to clarify the syntax. Maybe data() should return a list of variables that model() picks up (even if internally it doesn't)? Not sure, let me know if you have any suggestions.

Shall we close this?

**Comment by jstypka** [comment]
Sure. I'm quite flooded with work lately, but I will try to have a look and think about it when I have time. Cheers :)

**Comment by maxpumperla** [comment]
Hey @jstypka, this issue was really bugging me. Release 0.1.0 now mimicks actual python functions, data() "suggests" to feed into model(), which should make intuitive sense.  Let me know what you think. You seem to have a good hold on such things. M

**Comment by jstypka** [comment]
Hmmm, it's definitely better, however if I understand the code correctly - it still doesn't matter really what you return and what the model takes as an argument, it only gives an impression that something is really passed. Is that right?

What crossed my mind, however I'm not sure if it's feasible, is to encapsulate the `data` function in some kind of a scope that would make the whole thing a little bit more resistant to potential side effects. So imagine a programmer by accident uses a variable in `model` function that has not been defined in this function, however it has been coincidentally defined in the `data` function. If I read the code right, the program will work and behave in a weird way instead of failing which can be super hard to debug. Do you think it would be possible to use a structure like this:
```
data_result = None
if True:
    # inject the data code here
    # substitute the return XXX with:
    data_result = XXX

# and then do normal model things here
# using the data_result variable
```
Even though this `if` makes no sense, it encapsulates at least a bit the environment that the function is in and makes it impossible to access those variables later on. Or even better:
```
def user_data():
    # user data code
    # his return statement

data_result = user_data()
# and then do normal model things here
# using the data_result variable
```
You could also use `*args` or `**kwargs` to pass the arguments in between. Is that doable? I admit, I didn't investigate the code very thoroughly so I might have got a wrong impression.
