### ISSUE TITLE
ValueError: Incompatible shapes for broadcasting: (512,) and (?, 1024)

### ISSUE THREAD

**Issue by omarcr** [maxpumperla/hyperas#33]
when training the following model

> def model(Xtrain, Xtest, ytrain, ytest, nb_classes):
>     dims = Xtrain.shape[1]
>     #neurons = 2056
>     print('Building model...')
>     #neurons_all_layers = {{choice([256, 512, 1024, 2056])}}
>     #activation = {{choice([LeakyReLU(), LeakyReLU(), PReLU()])}}
>     model = Sequential()
>     model.add(Dense(2056, input_shape=(dims,)))
>     model.add({{choice([LeakyReLU(), LeakyReLU(), PReLU()])}})
>     model.add(BatchNormalization())
>     model.add(Dropout({{uniform(0, 1)}}))
> 
> ```
> model.add(Dense({{choice([256, 512, 1024, 2056])}}))
> model.add({{choice([LeakyReLU(), LeakyReLU(), PReLU()])}})
> model.add(BatchNormalization())
> model.add(Dropout({{uniform(0, 1)}}))
> ```

I get:
"ValueError: Incompatible shapes for broadcasting: (512,) and (?, 1024)"

Any recommendations on how to fix this?

**Comment by ismaeIfm** [comment]
I think is the same issue as this #32

**Comment by maxpumperla** [comment]
yes, it's indeed the same. I'm closing this for now. thanks
