### ISSUE TITLE
temp_model.py generation chops off commands from def data()

### ISSUE THREAD

**Issue by StuartFarmer** [maxpumperla/hyperas#37]
Running hyperas to a modified piece of keras data results in the following error:

`Unexpected error: <type 'exceptions.SyntaxError'>
Traceback (most recent call last):
  File "lstm-hyperas.py", line 165, in <module>
    trials=Trials())
  File "C:\Users\stuart\Anaconda2\lib\site-packages\hyperas\optim.py", line 31, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)
  File "C:\Users\stuart\Anaconda2\lib\site-packages\hyperas\optim.py", line 96, in base_minimizer
    from temp_model import keras_fmin_fnct, get_space
  File "C:\Users\stuart\Documents\Developer\Python\ForexPredictionV1\LSTM\temp_model.py", line 28
    h open(file_name, 'rU') as f:  #opens PW file
         ^
SyntaxError: invalid syntax`

Which makes sense when you look at the temp_model.py file that was created:

```
from keras.callbacks import ReduceLROnPlateau
from keras.regularizers import l2, activity_l2, l1, l1l2
from hyperopt import Trials, STATUS_OK, tpe
from hyperas import optim
import cPickle as pickle
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials
from hyperas.distributions import conditional

S_OUT = 15
e_name = 'output-final-150000.csv'
_data = []
h open(file_name, 'rU') as f:  #opens PW file
ader = csv.reader(f)
w_data = list(list(rec) for rec in csv.reader(f, delimiter=',')) #reads csv into a list of lists
close() #close the csv

onvert string values to floats using a buffer
fer = []
 x in range(len(raw_data)):
ffer.append([float(list_item) for list_item in raw_data[x]])

_data = buffer

ler = MinMaxScaler(feature_range=(0, 1))
_data = scaler.fit_transform(raw_data)

in_size = int(len(raw_data) * 0.67)
t_size = int(len(raw_data) * 0.33)

lace the data the day before in X and the day after (the one to predict) in Y
 raw_data[:-DAYS_OUT]

y_prices = []
 data in raw_data:
ly_prices.append(data[5])

 []
```

Hyperas chops off my commands. What? Code in keras_fmin_fnct(space) is unaltered.

**Comment by solidua** [comment]
I'm having the same issue as well...

**Comment by MatthiasWinkelmann** [comment]
The problem is in https://github.com/maxpumperla/hyperas/blob/master/hyperas/optim.py#L181. Most likely, you're using an indent != 4 spaces, in the case above it appears to be 2 spaces.
