### ISSUE TITLE
best parameters

### ISSUE THREAD

**Issue by beaunorgeot** [maxpumperla/hyperas#39]
Greetings. 
I can't figure out how to view the parameters of the best performing model after a run. 
Ideally, I'd like to be able to rank the models by performance (w/the params displayed). 
Are either of these possible? 

Forgive me if I've missed something in the docs or something obvious in the code, I'm not very python savvy.

**Comment by maxpumperla** [comment]
Greetings, please see the code here and the corresponding right documentation above it:

https://github.com/maxpumperla/hyperas/blob/master/hyperas/optim.py#L42

Is that helpful? Thanks
