### ISSUE TITLE
Error in Running Complete Example: SyntaxError: invalid syntax Unexpected error: <class 'SyntaxError'>

### ISSUE THREAD

**Issue by ErmiaAzarkhalili** [maxpumperla/hyperas#40]
Hi,
While I am running your complete example, I am getting the following error, and I do not know why?
I am on pycharm and default interpreter of its console is IPython.

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-26f427aab178>", line 66, in <module>
    trials=Trials())
  File "/usr/local/lib/python3.4/dist-packages/hyperas/optim.py", line 31, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)
  File "/usr/local/lib/python3.4/dist-packages/hyperas/optim.py", line 96, in base_minimizer
    from temp_model import keras_fmin_fnct, get_space
  File "/home/ermia/JetBrains/pycharm-2016.2/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/ermia/PycharmProjects/DeepLearning/temp_model.py", line 3, in <module>
    from _pydevd_bundle.pydevconsole_code_for_ironpython import InteractiveConsole
  File "/home/ermia/JetBrains/pycharm-2016.2/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/ermia/JetBrains/pycharm-2016.2/helpers/pydev/_pydevd_bundle/pydevconsole_code_for_ironpython.py", line 105
    except SyntaxError, err:
                      ^
SyntaxError: invalid syntax
Unexpected error: <class 'SyntaxError'>

**Comment by maxpumperla** [comment]
Hi, that problem seems to be related to `ipython`. Can you execute this as a regular script?

Btw, python 3 compatibility is blocked by the following:
https://github.com/hyperopt/hyperopt/issues/234

See also discussion here:
https://www.reddit.com/r/MachineLearning/comments/46myc4/hyperas_keras_hyperopt_a_very_simple_wrapper_for/

I tried my best to get in touch with the author of hyperopt and try to get write access to publish a new version, but I really can't do much about this problem as is (apart from forking hyperopt, which would be a bit silly).

**Comment by ErmiaAzarkhalili** [comment]
you/'re absolutely right, and do you have any ideas to support ipython
version?
Now, I get the following error:
TypeError: fmin() got an unexpected keyword argument 'rseed'

Which is completely familiar and visible in your links!
https://www.reddit.com/r/MachineLearning/comments/46myc4/hyperas_keras_hyperopt_a_very_simple_wrapper_for/

So ,we need to handle both problems: 1) IPython support for the code. 2)
Update the package for Python 3.

I will send him an official email to kindly ask him to release
pypi version for python 3 support.
It is so pity that your good package become useless due to other issue.



Sincerely,
Ermia
*------------------------------------------------------------------------------------------------------------*
Never lose the child-like wonder. It's just too important. It's what drives
us.

**Comment by ErmiaAzarkhalili** [comment]
I am almost sure that we will not get any reply on his behalf as he moved
to kindred.ai and there is no official recent emails by which we can access
to him.
What do you think? How can we utilize his code?

Sincerely,
Ermia
*------------------------------------------------------------------------------------------------------------*
Never lose the child-like wonder. It's just too important. It's what drives
us.

**Comment by maxpumperla** [comment]
Exactly, by now I think you realise how much effort and work it requires to resolve this issue. That's why I was a bit surprised by your initial request via twitter. I'm doing my best here. :)

To be honest, for python3 support, maybe I'll have to fork `hyperopt`, but that requires a lot of work.

Ipython (notebook) support requires a bit of a refactoring of the project, not sure if that's very high up on my priority list right now, I'm afraid.

**Comment by ErmiaAzarkhalili** [comment]
Thank you.
1) To me, forking might be fairly good idea. Your package is really
awesome, but people need python 3 support. Now, I am utilizing another
Bayesian optimization package, but it really take long time.
2) It would be great to refactor it, but you are the one who may decide.

Sincerely,
Ermia
*------------------------------------------------------------------------------------------------------------*
Never lose the child-like wonder. It's just too important. It's what drives
us.

**Comment by ErmiaAzarkhalili** [comment]
Hi Max,
It's great that you can maintain the code now.
hyperapt  and our package, hyperas, are unbelievably efficient, and I will
be waiting for your updated version of both hyperapt and hyperas.

Thanks a lot, I have no idea though how you could reach the developer of
hyperapt as I sent him many emails but have not received any reply. :)

Sincerely,
Ermia
*------------------------------------------------------------------------------------------------------------*
Never lose the child-like wonder. It's just too important. It's what drives
us.

**Comment by maxpumperla** [comment]
Ok, I'm closing this one, as you wrote another, more clear issue. thanks.

**Comment by maxpumperla** [comment]
And btw, I think the author of hyperopt contacted me because I specifically offered help. 👍

**Comment by ErmiaAzarkhalili** [comment]
Yeah, you're great man, I never doubt about your kindness.

I would be thankful if you could provide me his email to which you sent email.

⁣Best Regard,
Behrooz​
