### ISSUE TITLE
Error when running cifar_generator_cnn example:  ValueError: Filter must not be larger than the input

### ISSUE THREAD

**Issue by MannyKayy** [maxpumperla/hyperas#41]
I get a 
`ValueError: Filter must not be larger than the input: Filter: (2, 2) Input: (1, 30) `

when running the cifar_generator_cnn.py example.

Any recommendations on how to fix it?

Running using python 3 with a [fork](https://github.com/maexlich/hyperopt) of hyperopt that fixes the fmin issues

**Comment by maxpumperla** [comment]
Sorry, but would you please provide a bit more of the stack trace? Thank you. As is I have no idea what goes wrong. :)

**Comment by MannyKayy** [comment]
Alright, fixed by setting https://github.com/maxpumperla/hyperas/blob/master/examples/cifar_generator_cnn.py#L63

to

`input_shape=X_train.shape[1:]))`
