### ISSUE TITLE
Ensemble example - TypeError: 'map' object is not subscriptable 

### ISSUE THREAD

**Issue by MannyKayy** [maxpumperla/hyperas#42]
I'm running the examples  with Python 3. I've managed to get most of them running so far.

The mnist ensemble example breaks with Python3 and I would appreciate any recommendations on how to fix it.

`
Traceback (most recent call last):
  File "hypetest/mnist_ensemble.py", line 68, in <module>
    preds =ensemble_model.predict(X_test)
  File "/opt/conda/lib/python3.5/site-packages/hyperas/ensemble.py", line 36, in predict
    nb_classes = predictions[0].shape[1]
TypeError: 'map' object is not subscriptable
`

**Comment by maxpumperla** [comment]
Yes, this one I can help with immediately. 

https://github.com/maxpumperla/hyperas/blob/master/hyperas/ensemble.py#L34

In that line we use `map`, whose behaviour differs between python 2 and 3. I think the easiest to fix this is to explicitly cast `predictions` to a list , i.e. do 

```{python}
predictions = list(map(lambda model: model.predict(X, batch_size, verbose), self.model_list))
```

**Comment by maxpumperla** [comment]
By the way, you mentioned you fixed the hyperopt `fmin` inconsistencies for python3. Since this is also highly relevant for me, is there any way you can share this fix? Maybe I can fork hyperopt to pin that version to hyperas. Thanks!

**Comment by maxpumperla** [comment]
Ah, sorry. Just saw that you shared the link to the fork. Thanks for this.

**Comment by MannyKayy** [comment]
Alright, i cast the following to list and things seem to work. let me know if I' missing something.

(https://github.com/maxpumperla/hyperas/blob/master/hyperas/ensemble.py#L34)
(https://github.com/maxpumperla/hyperas/blob/master/hyperas/ensemble.py#L40)
(https://github.com/maxpumperla/hyperas/blob/master/hyperas/ensemble.py#L46)

I also changed https://github.com/maxpumperla/hyperas/blob/master/hyperas/ensemble.py#L36 to 
`nb_classes = len(predictions[0])`

**Comment by maxpumperla** [comment]
Do you want to create a pull request for this?

**Comment by MannyKayy** [comment]
Will do

**Comment by MannyKayy** [comment]
Fixed in pull request [#43](https://github.com/maxpumperla/hyperas/pull/46)

**Comment by YangBain** [comment]
@maxpumperla  Hello, 
:\Tesnsorflow\Weaklydetector\src>python train.caltech.py
Traceback (most recent call last):
File "train.caltech.py", line 44, in 
image_paths_train = np.hstack(map(lambda one_class: one_class[:-10], image_paths_per_label))
File "C:\Program Files\Anaconda3\lib\site-packages\numpy\core\shape_base.py", line 275, in hstack
arrs = [atleast_1d(_m) for _m in tup]
File "C:\Program Files\Anaconda3\lib\site-packages\numpy\core\shape_base.py", line 275, in 
arrs = [atleast_1d(_m) for _m in tup]
File "train.caltech.py", line 44, in 
image_paths_train = np.hstack(map(lambda one_class: one_class[:-10], image_paths_per_label))
TypeError: 'map' object is not subscriptable

:\Tesnsorflow\Weaklydetector\src>python train.caltech.py
Traceback (most recent call last):
File "train.caltech.py", line 40, in 
image_paths_train = np.hstack(list(map(lambda one_class: one_class[:-10], image_paths_per_label)))
File "train.caltech.py", line 40, in 
image_paths_train = np.hstack(list(map(lambda one_class: one_class[:-10], image_paths_per_label)))
TypeError: 'map' object is not subscriptable

Any idea of this problem? Thank you very much.

**Comment by maxpumperla** [comment]
@YangBain please don't use closed tickets for this. I've commented on your other issue. problem is on your side, I'm relatively sure.
