### ISSUE TITLE
nb_epoch > 1 ?

### ISSUE THREAD

**Issue by jesuisnicolasdavid** [maxpumperla/hyperas#5]
I am wondering why keras does not allow to search for hyperparameters through more than 1 epoch in every evaluation ? Can you explain a little the behaviour of the TPE algorithm in keras ? Thanks!

**Comment by maxpumperla** [comment]
I'm not exactly sure what you mean, you certainly can use nb_epoch > 1. Just go ahead and try modifying an example. I just put nb_epoch=1 in all examples so that you see results quicker.

**Comment by maxpumperla** [comment]
@jesuisnicolasdavid any luck so far?

**Comment by jesuisnicolasdavid** [comment]
I  just checked and in fact there is some kind of issue when running with a jupyter notebook : each time i want to change the number of epoch i have to hard_reset the kernel of the notebook. So everything is fine with hyperas ! Thanks !

**Comment by maxpumperla** [comment]
Great, glad to hear that!
