### ISSUE TITLE
import java.lang.System

### ISSUE THREAD

**Issue by bscully** [maxpumperla/hyperas#50]
Pyhon2.7 Windows64
Running the homepage's "complete example".
A file called temp_model.py is created and in line32 reads, "import java.lang.System"
which causes an error:

ImportError: No module named java.lang.System

**Comment by maxpumperla** [comment]
Can you execute one of the actual example files, like `simple.py`? This seems to come from jython, but we don't use that anywhere.

**Comment by bscully** [comment]
Thanks for the point that hyperas doesn't use java.  Made me think my IDE does - Eclipse.
When running via cmd, everything works (mostly).   I got an fmin() rseed error but just deleted that param and now runs successfully.

Package versions (which I believe are the latest):
hyperas (0.2)
hyperopt (0.1)
Keras (1.1.2)

**Comment by maxpumperla** [comment]
Thanks @bscully for coming back on this, that's very interesting. In fact, I want to support all IDEs as well. We have another issue open in which there's similar problems with pycharm.

Can you see other problems or is it "just" the java lang thing?

**Comment by maxpumperla** [comment]
@bscully would you be so kind to install master and check if it works with Eclipse. We now ignore everything that contains `java.lang`.

**Comment by maxpumperla** [comment]
@bscully can you run the basic examples from within eclipse now with current master? I can run stuff in pycharm.

**Comment by bscully** [comment]
I installed master and got past the java error but am now presented with another:

## -- End pasted text --
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-171a65b705e3>", line 5, in <module>
    trials=Trials())
  File "C:\Python27\lib\site-packages\hyperas-0.3-py2.7.egg\hyperas\optim.py", line 42, in minimize
    notebook_name=notebook_name, verbose=verbose)
  File "C:\Python27\lib\site-packages\hyperas-0.3-py2.7.egg\hyperas\optim.py", line 62, in base_minimizer
    model_str = get_hyperopt_model_string(model, data, notebook_name, verbose, stack)
  File "C:\Python27\lib\site-packages\hyperas-0.3-py2.7.egg\hyperas\optim.py", line 125, in get_hyperopt_model_string
    with open(calling_script_file, 'r') as f:
IOError: [Errno 22] invalid mode ('r') or filename: 'C:\\Eclipse\\<ipython-input-8-171a65b705e3>'


Note: this is via console.  When running through cmd.exe, everything runs fine :)

**Comment by ErmiaAzarkhalili** [comment]
Hi there,
Hence it's a serious issue and it's IDE-independent problem...

Indeed, when I am running in Linux terminal, everything looks great, but it does not work via Python console in pycharm...

**Comment by maxpumperla** [comment]
I will consolidate all these IDE problems in one new issue. Right now hyperas simply does not work with pycharm or spyder.
