### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by jdelange** [maxpumperla/hyperas#57]
First time try with Hyperas. I get an error: **object of type 'NoneType' has no len()** at `trials=Trials() `in the `optim.minimize(...)` call. Not sure what this means. I am trying to optimize a network that takes three inputs in the form of a list X_train[], so X_train[0] has a set of input data, X_train[1] and X_train_[2] also.  Not sure if that could be the cause for this error? Don't know what Hyperas can handle.

Here's some code:

```
def data(): 
    # load VGG16 output data, X_train and X_valid are lists with data channels
    X_train, Y_train, X_valid, Y_valid = load_VGG16_output(data_type='train', num_channels=3)
    return X_train, Y_train, X_valid, Y_valid
```
```
def model(X_train, Y_train, X_valid, Y_valid):

    in_0 = Input(shape=X_train[0].shape[1:])    
    x = Dense(256, activation='relu')(in_0)
    x = Dropout(0.5)(x)

    in_1 = Input(shape=X_train[1].shape[1:])
    y = Dense(64, activation='relu')(in_1) #, W_regularizer=l2(0.01))(in_1)
    y = Dropout(0.5)(y)

    in_2 = Input(X_train[2].shape[1:])
    z = Dense(32, activation='relu')(in_2) #, W_regularizer=l2(0.01))(in_2)
    z = Dropout(0.5)(z)

    x = merge([x, y, z], mode='concat', concat_axis=1)
    
    predict = Dense(1, activation='sigmoid')(x)
    model = Model(input=[in_0, in_1, in_2], output=predict)
   
    optimizer=Adam(lr=1e-4, decay=0.003)

    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

    # load the class weight to balance the input positive / negative scores
    class_weight = load_class_weight()

    model.fit(X_train, Y_train,
              batch_size={{choice([32, 64, 128])}}, # optimize batch size
              nb_epoch=1, 
              verbose=2, 
              class_weight=class_weight,
              validation_data=(X_valid, Y_valid))

    score, acc = model.evaluate(X_valid, Y_valid, verbose=0)
    print('Valid accuracy: ', acc)
    return {'loss': -acc, 'status': STATUS_OK, 'model': model}
```
```
if __name__ == '__main__':
    
    X_train, Y_train, X_valid, Y_valid = data()

    best_run, best_model = optim.minimize(model=model,
                                          data=data,
                                          algo=tpe.suggest,
                                          max_evals=5,
                                          trials=Trials())
       
    print('Evalutation of best performing model: ')
    print(best_model.evaluate(X_valid, Y_valid))
```

**Comment by maxpumperla** [comment]
@jdelange could you please provide the full stack trace?

**Comment by jdelange** [comment]
Max, see below. The example Mnist example runs, so the system set-up should be ok. I tried the model with one channel input only, but that gives the same error, so it's probably something else.

Using Theano backend.
Using gpu device 0: GeForce GTX 960 (CNMeM is enabled with initial size: 95.0% o
f memory, cuDNN 5005)
------------------------------
Load VGG16 model output data...
------------------------------
>>> Imports:
from __future__ import print_function, division

try:
    import os
except:
    pass
try:
    import h5py
except:
    pass
try:
    import sys
except:
    pass
try:
    import numpy
except:
    pass
try:
    from PIL import Image
except:
    pass
try:
    import matplotlib.pyplot
except:
    pass
try:
    from CropImageFromMask import export_prediction
except:
    pass
try:
    from VGG16mod2 import VGG16
except:
    pass
try:
    from myUtils import load_vars
except:
    pass
try:
    from hyperopt import Trials, STATUS_OK, tpe
except:
    pass
try:
    from hyperas import optim
except:
    pass
try:
    from hyperas.distributions import choice, uniform, conditional
except:
    pass
try:
    from keras.models import Model, Sequential
except:
    pass
try:
    from keras.layers import Convolution2D, MaxPooling2D, ZeroPadding2D, GlobalA
veragePooling2D
except:
    pass
try:
    from keras.layers import Activation, Dropout, Flatten, Dense, Input, merge
except:
    pass
try:
    from keras.callbacks import History, EarlyStopping, ModelCheckpoint
except:
    pass
try:
    from keras.optimizers import RMSprop, Adam, SGD
except:
    pass
try:
    from keras.preprocessing.image import ImageDataGenerator
except:
    pass
try:
    from keras.regularizers import l2
except:
    pass

>>> Hyperas search space:

def get_space():
    return {
        'batch_size': hp.choice('batch_size', [32, 64, 128]),
    }

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\Extensio
ns\Microsoft\Python Tools for Visual Studio\2.1\visualstudio_py_util.py", line 1
06, in exec_file
    exec_code(code, file, global_variables)
  File "C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\Extensio
ns\Microsoft\Python Tools for Visual Studio\2.1\visualstudio_py_util.py", line 8
2, in exec_code
    exec(code_obj, global_variables)
  File "D:\Data\Essential\Programming\Python\Keras\VGG16classHyper\VGG16classHyp
er\VGG16classHyper.py", line 258, in <module>
    trials=Trials())
  File "C:\Program Files\Anaconda2\lib\site-packages\hyperas\optim.py", line 42,
 in minimize
    notebook_name=notebook_name, verbose=verbose)
  File "C:\Program Files\Anaconda2\lib\site-packages\hyperas\optim.py", line 62,
 in base_minimizer
    model_str = get_hyperopt_model_string(model, data, notebook_name, verbose, s
tack)
  File "C:\Program Files\Anaconda2\lib\site-packages\hyperas\optim.py", line 137
, in get_hyperopt_model_string
    data_string = retrieve_data_string(data, verbose)
  File "C:\Program Files\Anaconda2\lib\site-packages\hyperas\optim.py", line 160
, in retrieve_data_string
    indent_length = len(determine_indent(data_string))
TypeError: object of type 'NoneType' has no len()
Press any key to continue . . .
![hyperas err screen](https://cloud.githubusercontent.com/assets/12218726/21079585/278237fe-bf96-11e6-9859-924a0058bf17.gif)

**Comment by maxpumperla** [comment]
the `determine_indent` function returns `None`, which indeed has no length, whenever you're using inconsistent indentation in your file. At least that's a possibility. In any case, the error message should be more clear.

**Comment by jdelange** [comment]
Thanks. So I need to check the indentation of the source file(s)? Typically the VS editor complains if indentation is incorrect, but I can have a look. I think I can change settings from spaces to tabs etc. I assume tabs is preferable as differences may be more obvious.
What do you mean with "should be more clear"? I assume that is not expected of me to change?
I will check indentation and revert. Thanks for the help. Jan

**Comment by maxpumperla** [comment]
I mean the `determine_indent` function should not silently return `None`, breaking the code, but instead throw a useful error message. Something I have to fix! :)

Let me know if it's indeed an indentation problem. Otherwise I'll investigate further.

@MatthiasWinkelmann you authored above function. Any idea what might be the root cause?

**Comment by jdelange** [comment]
I re-indented the source file with tabs, but to no avail. Same error.

**Comment by maxpumperla** [comment]
In this case, could you send your complete file so I can reproduce the error?

**Comment by jdelange** [comment]
Yes, appreciate your effort. Would you need the input data to run the program, then I need a means to get it to you. Suggestions? Will be tomorrow afternoon (Amsterdam time).

**Comment by maxpumperla** [comment]
It doesn't have to be this particular example, just a minimal version of it having this error. Does the stuff in the `example` folder work for you?

If stripping it down is too much work and you can't paste it her, use my firstname dot lastname at gmail com.

**Comment by MatthiasWinkelmann** [comment]
Oh, very sorry if I caused this. I'm writing a few tests right now and will try to reproduce.

**Comment by MatthiasWinkelmann** [comment]
I've tried to reproduce, and while I haven't succeeded in getting `TypeError: object of type 'NoneType' has no len()`, I did get some strange behaviour that might be related.

@jdelange: could you try to remove all comments, and all empty lines in `data()` and `model(..)`?

Hyperas (tries to) parse these two functions and creates a new source file (`temp_model.py`) to run. That mechanism is, unfortunately, a bit brittle. Another problem in this case may be the Windows linebreaks (`\r\n`), although I've tried and (surprisingly) failed to provoke an error with these.

My try to reproduce is in https://github.com/MatthiasWinkelmann/hyperas/blob/issue-57/tests/fixtures/issue-57.py. That file gives me an error 'Exception: Input 0 is incompatible with layer dense_1: expected ndim=2, found ndim=4' which means it's gotten beyond the point where the error you've seen happens.

**Comment by maxpumperla** [comment]
@MatthiasWinkelmann very good points. I also agree that current approach is brittle and unreliable. If you have good ideas how to inspect and modify `data` and `model` code (preferably in memory) without going through that business, I'm more than happy to discuss and refactor from ground up.

**Comment by jdelange** [comment]
I will try to provide you with something simple. Different error but perhaps related[#51](https://github.com/maxpumperla/hyperas/issues/51url) This is the standard example (that actually runs) but extended to get the optimization history (that does not run).

**Comment by jdelange** [comment]
@MatthiasWinkelmann on your trial: my trial fails also with one channel input, so that may make testing / searching a bit less complicated. Anyway I will strip mine to the bare essentials. Interesting to know the process behind the scenes.

**Comment by jdelange** [comment]
Sent a simplified model with data input files via Wetransfer. Error I am getting: 

> IndentationError was unhandled by user code Message: expected an indented block (temp_model.py, line 79)

**Comment by maxpumperla** [comment]
Sorry, I can't reproduce this, but I think this has been resolved. @jdelange please re-open if the problem still persists.

**Comment by ileadall42** [comment]
I got it! There is an indent after the `def data(): ` funtion as follow
![image](https://user-images.githubusercontent.com/27263086/71950005-ace86b80-3210-11ea-8cb7-57856477ebaf.png)
