### ISSUE TITLE
inspect.getsource(model) not working in optim.py , getting IOError: could not get source code, 

### ISSUE THREAD

**Issue by arvinder-singh** [maxpumperla/hyperas#59]
Hi @maxpumperla , I was just trying to run the codes in example folder but all executions failing at inspect.getsource(model) in optim.py .
Could you please advise.

Below is the error dump.

File "C:\Users\Singh\Anaconda2new\lib\site-packages\hyperas\optim.py", line 114, in get_hyperopt_model_string
    model_string = inspect.getsource(model)
  File "C:\Users\Singh\Anaconda2new\lib\inspect.py", line 701, in getsource
    lines, lnum = getsourcelines(object)
  File "C:\Users\Singh\Anaconda2new\lib\inspect.py", line 690, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\Users\Singh\Anaconda2new\lib\inspect.py", line 538, in findsource
    raise IOError('could not get source code')
IOError: could not get source code

**Comment by maxpumperla** [comment]
usually people have these problems when using IDEs, is that the case for you? We currently do not support spyder, pycharm & co., as it does not work well with hyperas' approach, unfortunately. Otherwise, please try updating your python libs and install hyperas directly from master.

**Comment by LeZhengThu** [comment]
Hi, I'm not using any IDEs and still get the error. Do you guys have any idea? Thanks in advance.
