### ISSUE TITLE
problems when model() and data() are copied to temporary file

### ISSUE THREAD

**Issue by mjdietzx** [maxpumperla/hyperas#60]
```python
optim.minimize(model=train_model, data=return_datasets,
```
problem is hyperas seems to copy the `train_model()` and `return_datasets()` functions to a temporary python file.

This causes a few problems:
1.) If there are helper functions in `train_model()` or `return_datasets()` defined in the same module they are lost.
2.) Global variables used in `train_model()` or `return_datasets()` are lost.

**Comment by leocnj** [comment]
Just found the same issue as reported above.

**Comment by Bassel1** [comment]
did you see a solution for that?

**Comment by trane293** [comment]
Same issue here. I need to keep track of the number of evaluations that are done to save model snapshots for each evaluation run, but the global variables all return errors when the functions are copied to temporary files. Haven't found a solution yet, will post if I do.

**Comment by jaggzh** [comment]
I'm having the same issue, and another similar one (https://github.com/maxpumperla/hyperas/issues/75).
It seems the initial parsing takes imports, although it modifies some (like "import numpy as np" is changed to just "import numpy"), and global variable declarations/assignments are not included at all.  I can't find documentation on this; are there docs somewhere on this all?

**Comment by trane293** [comment]
I forgot to post my (hacky) solution to the problem of losing global variables when the code is copied to a temporary file. What is do is to create a globalvars.py file where I define - 

`globalVar = 0`

Copy this to the folder where your script is residing. Then in your Hyperas script do this:

`import globalvars`

Use the global variable - globalvars.globalVar as the global variable. It will retain the value inside it throughout the program execution, and you can change the values too - 

`globalvars.globalVar += 1`

**Comment by jaggzh** [comment]
I made a change for, at least, fixing the "import foo as bar" lines.  Please let me know if you have problems with it.  So far it's working for me, but I'm working on passing global variables through as well, so I can't do full testing of my actual project scripts until I get that done (or rewrite them using the import hack trane293 offered).

To allow "import as" lines, edit utils.py and go to the InputParser class, and change the visitImport() function to:
    def visit_Import(self, node):
        # import a, .. z with optional "a as alias" items
        # Let's make this line tight and hard to read:
        line = 'import ' \ 
            + ', '.join([ '{} as {}'.format(n.name, n.asname) if n.asname \
                else n.name for n in node.names ])
        # Old version which didn't handle aliases (asname's):
        # line = 'import {}'.format(self._import_names(node.names))
        self.line_numbers.append(node.lineno)
        self.lines.append(line)

**Comment by maxpumperla** [comment]
@mjdietzx @jaggzh @leocnj @trane293 the issue with import aliases has been fixed in master, will release a new version soon. until then, please install from github directly. Also, the issue of losing helper functions along the way can be addressed like this:
```
https://github.com/maxpumperla/hyperas/blob/master/examples/use_intermediate_functions.py
```

Other than that, stuff being copied to a temp file _is what runs hyperas_, so it's really essential to the implementation right now. That approach has certain limitations. As you find yourself having problems, please just use hyperopt with keras. Hyperas is for quick experimentation only.
