### ISSUE TITLE
bug parsing inline comments

### ISSUE THREAD

**Issue by mjdietzx** [maxpumperla/hyperas#61]
```python
optim.minimize(model=model, data=data
```

If there is a comment like this:
```python
# Comment in model() or data() functions that are parsed by hyperas
```

the parser throws an indent error.

**Comment by brannondorsey** [comment]
This indeed appears to be a bug. The comments 
`# If we choose 'four', add an additional fourth layer` and `# We can also choose between complete sets of layers` in the __complete example__ in the README cause this error as well.

**Comment by pkainz** [comment]
@brannondorsey If you can move the `#` prefixed comments out of the function call, you can use docstrings `"""A comment..."""` as a temporary workaround until this issue is fixed.

**Comment by pkainz** [comment]
This issue seems to be fixed in the current master branch. I encountered it just on the `0.3` version from PyPI. 
Install the package from the git source to avoid this issue, something like:
```bash
git clone https://github.com/maxpumperla/hyperas ~/code
cd ~/code/hyperas
python setup.py install
```
