### ISSUE TITLE
varying convolution filter sizes

### ISSUE THREAD

**Issue by kirk86** [maxpumperla/hyperas#62]
Hi and thanks for this wrapper. I have one question. From the examples is not very clear whether it's possible to vary the sizes of the filters in convolution layers? Is that doable?

**Comment by achigeor** [comment]
@kirk86 Hey! I'm interested in that too. Did you find out if it's doable?

**Comment by pkainz** [comment]
In your model architecture definition use a `choice` selector for the kernel size, e.g.
```python
# ...
model.add(
    Conv2D(filters=32, 
           kernel_size={{choice([(3, 3), (5,5)])}})
)
# ...
```
