### ISSUE TITLE
NameError in import foo as bar

### ISSUE THREAD

**Issue by ismaeIfm** [maxpumperla/hyperas#65]
Hi, every time I used the syntax:
`import foo as bar` I got a NameError: name 'foo' is not defined.

I noticed with `import numpy as np`. I'm using hyperas==0.3 and hyperopt==0.1.

**Comment by nicholasbutlin** [comment]
plus 1

**Comment by maxpumperla** [comment]
this has been fixed in master, will try to release a new version soon.
