### ISSUE TITLE
error importing optim

### ISSUE THREAD

**Issue by kirk86** [maxpumperla/hyperas#66]
Hi, I've been having this issue when trying to run the example test case. 

```
 File "hyperas.py", line 3, in <module>
    from hyperas import optim
  File "/home/user/hyperas.py", line 3, in <module>
    from hyperas import optim
ImportError: cannot import name optim
```
By inspecting line 3, I don't see any errors, furthermore when I just fire up the ipython shell and execute `from hyperas import optim` it works fine. What I've noticed though is that I cannot execute the example if I move it to any other location on my pc besides the `/home/use/`default user directory. Any thoughts?

**Comment by bzamecnik** [comment]
Your example source is located in `hyperas.py` which conflicts with the package `hyperas`. Try to rename your example. The exactly same thing happened to me and that was the solution. :)

**Comment by kirk86** [comment]
@bzamecnik thanks a bunch..
