### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by eygrr** [maxpumperla/hyperas#67]
Hey, I just installed on python 3.4.2 and I'm using the PyCharm IDE. I've opened the example file in my ide and attempted to run it. The following error occurs:

```
Using Theano backend.
Traceback (most recent call last):
  File "D:/Dropbox/Dropbox/PhD/My Work/Code/Paper 2/src/temp.py", line 77, in <module>
    trials=Trials())
  File "C:\Anaconda3\envs\py34\lib\site-packages\hyperas\optim.py", line 42, in minimize
    notebook_name=notebook_name, verbose=verbose)
  File "C:\Anaconda3\envs\py34\lib\site-packages\hyperas\optim.py", line 62, in base_minimizer
    model_str = get_hyperopt_model_string(model, data, notebook_name, verbose, stack)
  File "C:\Anaconda3\envs\py34\lib\site-packages\hyperas\optim.py", line 132, in get_hyperopt_model_string
    imports = extract_imports(cleaned_source, verbose)
  File "C:\Anaconda3\envs\py34\lib\site-packages\hyperas\utils.py", line 31, in extract_imports
    tree = ast.parse(source)
  File "C:\Anaconda3\envs\py34\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 35
    if conditional({{choice(['three', 'four'])}}) == 'four':
    ^
IndentationError: unexpected indent
```

I understand that this may be because there is a mixing of tabs and spaces? I will be attempting to resolve it under that understanding next and update here if that is the case.

**Comment by eygrr** [comment]
I tried replacing the tabs with spaces in my own example file and it didn't work.

**Comment by tfriedel** [comment]
I have the same problem with python 2.7.

**Comment by tfriedel** [comment]
Seems to be a bug with the function that stripts the source of comments. 
This is part of the input source: 
`
    model.add(Dropout({{uniform(0, 1)}}))

    # If we choose 'four', add an additional fourth layer
    if conditional({{choice(['three', 'four'])}}) == 'four':
        model.add(Dense(100))
        # We can also choose between complete sets of layers
        model.add({{choice([Dropout(0.5), Activation('linear')])}})
        model.add(Activation('relu'))

    model.add(Dense(10))
    model.add(Activation('softmax'))
`

And this is the output:
`
    model.add(Dropout({{uniform(0, 1)}}))

        if conditional({{choice(['three', 'four'])}}) == 'four':
        model.add(Dense(100))
                model.add({{choice([Dropout(0.5), Activation('linear')])}})
        model.add(Activation('relu'))

    model.add(Dense(10))
    model.add(Activation('softmax'))
`

**Comment by peroon** [comment]
I commented out and worked.

```
    """
    # If we choose 'four', add an additional fourth layer
    if conditional({{choice(['three', 'four'])}}) == 'four':
        model.add(Dense(100))
        # We can also choose between complete sets of layers
        model.add({{choice([Dropout(0.5), Activation('linear')])}})
        model.add(Activation('relu'))
    """
```

**Comment by justiceamoh** [comment]
I am having the same issues and commenting out isn't helping. I also see it with the data function:

```python
def data():
    (X_train, y_train), (X_test, y_test) = mnist.load_data()
    nb_class = 10

    # Reshape X data from 2D to 1D (28x28 to 784)
    X_train = X_train.reshape(60000,784).astype('float32')
    X_test  = X_test.reshape(10000,784).astype('float32')

    X_train /= 255
    X_test /= 255    

    # Convert Y labels to Categorical One-Hot Format
    y_train = np_utils.to_categorical(y_train, nb_class)
    y_test = np_utils.to_categorical(y_test, nb_class)

    return X_train, y_train, X_test, y_test
```

And the error code is:
```python
 File "<unknown>", line 29
    X_train = X_train.reshape(60000,784).astype('float32')
    ^
IndentationError: unexpected indent
```

I saw #54 but it's not clear from there how to rectify the issue.

**Comment by justiceamoh** [comment]
Actually, I realize this bug has been fixed in `master`. So don't use the standard pip version, **install directly from `master` to rectify the issue**.

**Comment by tfriedel** [comment]
If you remove all comments ( # .... ) from your code, it will work. Of course this is only a short term workaround and I hope remove_all_comments will get fixed properly.

**Comment by abourai** [comment]
Any change this change can get added to pip as well soon?

**Comment by pianomanu** [comment]
So is this version not uo to date?  https://pypi.python.org/pypi/hyperas/0.3

Sorry for the dummy question but how can I install directly from ```master``` ? 
Thanks in advance

**Comment by justiceamoh** [comment]
Yes, the pip version is not up to date. And, there's no such things as a dummy question :)

`pip install git+https://github.com/maxpumperla/hyperas.git@master`

**Comment by pianomanu** [comment]
Thanks a lot ! 
Weirdly enough, it says requirement already satisfied for all packages..

**Comment by SergioChevtchenko** [comment]
I used --upgrade option to update my previously installed version from pip. Otherwise it says requirement already satisfied for all packages. 

pip install git+https://github.com/maxpumperla/hyperas.git@master --upgrade

**Comment by maxpumperla** [comment]
above PR was just merged and shows an example of how to run an example without any of the issues.

**Comment by maxpumperla** [comment]
I think this is resolved, please re-open in case I'm wrong! thanks

**Comment by Leonardojessica** [comment]
Ola amigos estou com mesmo problema sera que podiam me ajudar 

> import speech_recognition as sr


  r = sr.Recognizer()
  with sr.Microphone() as source:
      print('Digo algo!')
      audio = r.listem(source)

  try:
      print('você disse: ' + r.recognizer_google(audio, language= "pt-br"))
  except sr.UnknowValueError:
      print("Ana não pode entender o audio")
  except sr.RequestError as e:
      print("Erro ao chamar google speech recognition service; {e}".format(e))

**Comment by porterchild** [comment]
I had the same issue, I solved it by changing my tab-indented file to a 4 space-indented file.
