### ISSUE TITLE
Optimize hyperparameters in data function

### ISSUE THREAD

**Issue by birnbaum** [maxpumperla/hyperas#68]
Is it somehow possible to not only optimize hyperparameters in the model, but also in the `data()` function?
The documentation at `data()` says:
> This function is separated from model() so that hyperopt
    won't reload data for each evaluation run.

However when I e.g. search for the perfect sequence length in a RNN model, this is exactly what I want.
The sequence length does not only influence the model but also the preprocessing of the data so it needs to be regenerated for each evaluation run.

Thanks in advance :)

**Comment by birnbaum** [comment]
Hey Oliver,

I've been there as well. Unfortunately the trick behind hyperas is parsing and the sourcefile and creating multiple copies of the data function with the parameters replaced. Having wrapper functions breaks this because of the additional indentation.

This approach seems very hacky to me and for sure it's not very flexible. I ended up using hyperopt directly which is a very nice and easy to use libary.

**Comment by maxpumperla** [comment]
@birnbaum exactly, please use plain hyperopt for more intricate use cases. I'll write a tutorial for this soon. Hyperas, from the very beginning, was intended for quick experimentation only. The only true benefit, while being brittle, is that you only have to maintain hyperparameters in one place.

**Comment by maxpumperla** [comment]
@birnbaum  there is new functionality available for intermediate functions as described by @ben0it8 above, which you can find exemplified here:

https://github.com/maxpumperla/hyperas/blob/master/examples/use_intermediate_functions.py

hope this helps.

**Comment by maxpumperla** [comment]
please feel free to re-open in case that's not sufficient. thanks
