### ISSUE TITLE
why appear the wrong  about the trials()  ? 

### ISSUE THREAD

**Issue by hbyido** [maxpumperla/hyperas#71]
why appear the wrong?
the code:

========================================

`

from __future__ import print_function
from hyperopt import Trials, STATUS_OK, tpe
from hyperas import optim
from hyperas.distributions import choice, uniform, conditional

from keras.utils import np_utils

import numpy
import matplotlib.pyplot as plt
import pandas
import math
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

def create_dataset(dataset):

    import numpy
    dataX, dataY = [],[]
    look_back = 3
    for i in range(len(dataset)-look_back-1):
        a = dataset[i:(i+look_back), 0]
        dataX.append(a)
        dataY.append(dataset[i + look_back, 0])
    return numpy.array(dataX), numpy.array(dataY)

def data():

    import pandas
    
    dataframe = pandas.read_csv('internationalairlinepassengers.csv', usecols=[1], engine='python', skipfooter=3)
    dataset = dataframe.values
    dataset = dataset.astype('float32')
    scaler = MinMaxScaler(feature_range=(0, 1))
    dataset = scaler.fit_transform(dataset)
    
    train_size = int(len(dataset) * 0.67)
    test_size = len(dataset) - train_size
    train, test = dataset[0:train_size,:], dataset[train_size:len(dataset),:]
    look_back = 3
    trainX, trainY = create_dataset(train)
    testX, testY = create_dataset(test)
    trainX = numpy.reshape(trainX, (trainX.shape[0], trainX.shape[1], 1))
    testX = numpy.reshape(testX, (testX.shape[0], testX.shape[1], 1))
    
    return trainX,trainY,testX,testY

def modelk(trainX,trainY,testX,testY):
    
    import math
    numpy.random.seed(7)
    from keras.models import Sequential
    from keras.layers import Dense
    from keras.layers import LSTM
    model = Sequential()
    model.add(LSTM({{choice([4,6])}},input_shape=(look_back, 1)))
    model.add(Dense(1))
    model.compile(loss='mean_squared_error', optimizer='adam')
    model.fit(trainX,trainY,nb_epoch=100, batch_size=1,show_accuracy=true,verbose=2,validation_data=(testX,testY))
    score,acc = model.evaluate(testX,testY,show_accuracy=true,verbose=0)
    print('Test accuracy:', acc)
    return{'loss': -acc, 'status': STATUS_OK, 'model': model}

if __name__ == '__main__':
    trainX, trainY, testX, testY = data()
    best_run, best_model = optim.minimize(model=modelk,
                                          data=data,
                                          algo=tpe.suggest,
                                          max_evals=5,
                                          trials=Trials())
    
    print(best_run)
    print("Evalutation of best performing model:")
    print(best_model.evaluate(testX, testY))`
========================

![image](https://cloud.githubusercontent.com/assets/10874773/23910394/8cff9212-0914-11e7-9b51-f2e52e7af92f.png)

**Comment by maxpumperla** [comment]
you can resolve this using the new `function` argument like in this example:

https://github.com/maxpumperla/hyperas/blob/master/examples/use_intermediate_functions.py

**Comment by WUhailing** [comment]
I got TypeError: minimize() got an unexpected keyword argument 'functions'  and then I checked module info,
?optim.minimize
Signature: optim.minimize(model, data, algo, max_evals, trials, rseed=1337, notebook_name=None, verbose=True)
so there is no keyword 'functions' in hyperas 0.3?

**Comment by maxpumperla** [comment]
yes, it's not in 0.3 yet. you have to install from master! thanks
