### ISSUE TITLE
Underlying HyperOpt implementation is throwing ValueError

### ISSUE THREAD

**Issue by vdabravolski** [maxpumperla/hyperas#72]
Hi, 

I have a CNN with set of shared layers and multiple output layers/losses. It looks like in this network architecture the underlying HyperOpt is not able to properly handle the set of multiple loss functions on the evaluation step. 

Find below the code of the model and the stack trace which I'm getting on the evaluation step. Please note that the training of first model with random parameter is going fine. The issue appears only during evaluation.

**Model code**
```
def model(X_train, Y_train, X_test, Y_test):
    '''
    Model providing function:

    Create Keras model with double curly brackets dropped-in as needed.
    Return value has to be a valid python dictionary with two customary keys:
        - loss: Specify a numeric evaluation metric to be minimized
        - status: Just use STATUS_OK and see hyperopt documentation if not feasible
    The last one is optional, though recommended, namely:
        - model: specify the model just created so that we can later use it again.
    '''

    numpy.random.seed(1337)
    nb_classes = 11
    sequence_length = 5
    img_rows, img_cols, img_depth = 64, 64, 3
    input_shape = (img_rows, img_cols, img_depth)

    batch_size = 128
    #nb_epoch = 12 # original value. 1 is for debugging only.
    nb_epoch = 1
    nb_filters = 32
    pool_size = (2, 2)
    kernel_size = (3, 3)
    cls_weights = [1., 1., 1., 1., 1., 1., 1.]


    main_input = Input(shape=input_shape, dtype='float32', name='main_input')
    shared = Convolution2D(nb_filters, kernel_size[0], kernel_size[1],
                           border_mode='valid', input_shape=input_shape)(main_input)
    shared = Activation('relu')(shared)
    shared = Convolution2D(nb_filters, kernel_size[0], kernel_size[1])(shared)
    shared = Activation('relu')(shared)
    shared = MaxPooling2D(pool_size=pool_size)(shared)
    # shared = Dropout(0.25)(shared)
    shared = Dropout({{uniform(0, 1)}})(shared)
    shared = Flatten()(shared)
    shared = Dense(128)(shared)
    shared = Activation('relu')(shared)
    shared = Dropout(0.5)(shared)


    length_cls = Dense((sequence_length + 1))(shared)  # to account for sequence length + 1
    length_cls = Activation('softmax', name="length_cls")(length_cls)

    # 2. First digit classifier
    first_cls = Dense(nb_classes)(shared)
    first_cls = Activation('softmax', name="first_cls")(first_cls)

    # 3. Second digit classifier
    second_cls = Dense(nb_classes)(shared)
    second_cls = Activation('softmax', name="second_cls")(second_cls)

    # 4. Third digit classifier
    third_cls = Dense(nb_classes)(shared)
    third_cls = Activation('softmax', name="third_cls")(third_cls)

    # 5. Forth digit classifier
    forth_cls = Dense(nb_classes)(shared)
    forth_cls = Activation('softmax', name="forth_cls")(forth_cls)

    # 6. Fifth digit classifier
    fifth_cls = Dense(nb_classes)(shared)
    fifth_cls = Activation('softmax', name="fifth_cls")(fifth_cls)

    #7. Digit boxes coordinates regresssion
    coord_regr = Dense(20, name="coord_regr")(shared)

    # model compilation and training
    model = Model(input=[main_input], output=[length_cls, first_cls, second_cls, third_cls, forth_cls, fifth_cls, coord_regr])

    model.compile(loss={'length_cls': 'categorical_crossentropy', 'first_cls': 'categorical_crossentropy',
                        'second_cls': 'categorical_crossentropy', 'third_cls': 'categorical_crossentropy',
                        'forth_cls': 'categorical_crossentropy', 'fifth_cls': 'categorical_crossentropy',
                        'coord_regr': 'mean_squared_error'},
                  optimizer='adadelta',
                  metrics={'length_cls': 'accuracy', 'first_cls': 'accuracy',
                           'second_cls': 'accuracy', 'third_cls': 'accuracy',
                           'forth_cls': 'accuracy', 'fifth_cls': 'accuracy',
                           'coord_regr': iou_metric_func}, loss_weights=cls_weights)

    directory = "output/" + str(datetime.datetime.now())
    if not os.path.exists(directory):
        os.makedirs(directory)

    checkpointer = ModelCheckpoint(filepath=directory + "/weights.hdf5", verbose=1, save_best_only=True)
    tensorboard = TensorBoard(log_dir=directory, histogram_freq=0, write_graph=True, write_images=False)
    # Todo: add EarlyStopping callback
    # Todo: add LearningRateSchedule callback
    model.fit([X_train], Y_train, batch_size=batch_size, nb_epoch=nb_epoch,
              verbose=1, validation_data=([X_test], Y_test), callbacks=[checkpointer, tensorboard])

    score, acc = model.evaluate(X_test, Y_test, verbose=0)

    print('Test accuracy:', acc)
    return {'loss': -acc, 'status': STATUS_OK, 'model': model}


if __name__ == '__main__':
    best_run, best_model = optim.minimize(model=model,
                                          data=data,
                                          algo=tpe.suggest,
                                          max_evals=2,
                                          trials=Trials())
    X_train, Y_train, X_test, Y_test = data()
    print("Evalutation of best performing model:")
    print(best_model.evaluate(X_test, Y_test))
```

**Stack trace**
`Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/vadzimdabravolski/machine-learning/projects/digit_recognition/SVHM_grid_runner.py", line 176, in <module>
    trials=Trials())
  File "/anaconda/envs/data/lib/python2.7/site-packages/hyperas/optim.py", line 42, in minimize
    notebook_name=notebook_name, verbose=verbose)
  File "/anaconda/envs/data/lib/python2.7/site-packages/hyperas/optim.py", line 92, in base_minimizer
    rstate=np.random.RandomState(rseed))
  File "/anaconda/envs/data/lib/python2.7/site-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/anaconda/envs/data/lib/python2.7/site-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/anaconda/envs/data/lib/python2.7/site-packages/hyperopt/fmin.py", line 320, in fmin
    rval.exhaust()
  File "/anaconda/envs/data/lib/python2.7/site-packages/hyperopt/fmin.py", line 199, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/anaconda/envs/data/lib/python2.7/site-packages/hyperopt/fmin.py", line 173, in run
    self.serial_evaluate()
  File "/anaconda/envs/data/lib/python2.7/site-packages/hyperopt/fmin.py", line 92, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/anaconda/envs/data/lib/python2.7/site-packages/hyperopt/base.py", line 840, in evaluate
    rval = self.fn(pyll_rval)
  File "/Users/vadzimdabravolski/machine-learning/projects/digit_recognition/temp_model.py", line 195, in keras_fmin_fnct
ValueError: too many values to unpack`

**Comment by vdabravolski** [comment]
My bad, closing this. After further investigation the issue was in the code (in case of multiple losses model.evaluate returns a list of them, which can be assigned to 2 variables score and acc).

**Comment by ronykroy** [comment]
@vdabravolski  
Hi,
may I know how you handled this...?
could you please share some code...
I too am facing the same issue
