### ISSUE TITLE
Get list with hyperparameters and results

### ISSUE THREAD

**Issue by enavarrocomes** [maxpumperla/hyperas#76]
Hi!
Is there a way to obtain a dictionary / list / dataframe with all the models evaluated by the algorithm and its results, instead of just getting the best one? 
Thank you!

**Comment by pkainz** [comment]
Use a reference to the `hyperopt.Trials()` object you pass into the `hyperas.optim.minimize`. This contains the parameters at the property `misc`, and the results at `results`.
