### ISSUE TITLE
cannot import conditional ?

### ISSUE THREAD

**Issue by hanlianlu** [maxpumperla/hyperas#8]
Hi i've just copied your example from manual for some test,  it seems the 'conditional' cant be imported?

from hyperas.distributions import choice, uniform, conditional

ImportError: cannot import name conditional

**Comment by maxpumperla** [comment]
Yep, sorry didn't get around to make a new release. You have to work on master.

**Comment by maxpumperla** [comment]
Please upgrade to version 0.1.1., which fixes this issue.

**Comment by hanlianlu** [comment]
thank you， trying soon
