### ISSUE TITLE
How does it handle choices which are dimensionwise impossible?

### ISSUE THREAD

**Issue by Miail** [maxpumperla/hyperas#80]
I am currently trying to optimise CNN, some of the parameter combination can result in dimension wise imposibility... how does this handle this?

**Comment by jonhilgart22** [comment]
I'm pretty sure you have to check this in our code. For example, when choosing the number of filters you are using, and kernel size, you need to make sure that these settings will work with the dimensions of your image.

**Comment by maxpumperla** [comment]
@Miail you need to take care of this on your side. Hyperas is shorthand for Keras and Hyperopt, nothing more. So, if your combinations co-depend, make them a single `choice`, instead of two.
