### ISSUE TITLE
cannot import name 'conditional'

### ISSUE THREAD

**Issue by zhugejun** [maxpumperla/hyperas#9]
I encountered a problem when installing hyperas package by python 3.5. I posted this problem on (StackOverflow)[http://stackoverflow.com/questions/35978549/pip-install-hyperopt-and-hyperas-fail] and the problem was solved by `pip install git+https://github.com/hyperopt/hyperopt.git`. However, when I ran `from hyperas.distributions import choice, uniform, conditional`, it told me that `ImportError: cannot import name 'conditional'`. So I opened the `distributions.py` file and I found no `conditional` function.

**Comment by maxpumperla** [comment]
It's actually the same problem, conditional is in master but not yet in the latest release. So you could either do

```pip install git+https://github.com/maxpumperla/hyperas.git```

to install master or first clone and then install by

```
git clone https://github.com/maxpumperla/hyperas
cd hyperas
python setup.py install
```
I hope to release a new version of hyperas soon, which will resolve this issue. In any case, feel free to report such things here. I'm glad to help.

**Comment by maxpumperla** [comment]
Please upgrade to version 0.1.1., which fixes this issue.

**Comment by zhugejun** [comment]
Thanks for your help, Max. But I still got an error when running example `simple.py`.

`Traceback (most recent call last):
  File "simple.py", line 78, in <module>
    trials=Trials())
  File "/home/gejun/anaconda3/lib/python3.5/site-packages/hyperas-0.1.1-py3.5.egg/hyperas/optim.py", line 30, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials)
  File "/home/gejun/anaconda3/lib/python3.5/site-packages/hyperas-0.1.1-py3.5.egg/hyperas/optim.py", line 96, in base_minimizer
    trials=trials)
  File "/home/gejun/anaconda3/lib/python3.5/site-packages/hyperopt/fmin.py", line 306, in fmin
    return_argmin=return_argmin,
  File "/home/gejun/anaconda3/lib/python3.5/site-packages/hyperopt/base.py", line 625, in fmin
    return fmin_module.fmin(
AttributeError: 'function' object has no attribute 'fmin'
`
Is this the problem of hyperopt?

**Comment by maxpumperla** [comment]
That's a bug in hyperopt with py 3.4, see this for a patch:

https://github.com/hyperopt/hyperopt/issues/234

It's really a pity that hyperopt doesn't seem to be actively maintained anymore.

**Comment by zhugejun** [comment]
That works for me. I can run at least `simple.py` successfully. Thanks so much for your help.

**Comment by maxpumperla** [comment]
No problem, let me know if I can help with anything else.
